import CodeTheoryCryptoEquiv.CodingTheory.Dual

/-!
# Generator and parity-check matrices, and their duality

This module continues the coding-theory development of
`CodeTheoryCryptoEquiv/CodingTheory/LinearCode.lean` and
`CodeTheoryCryptoEquiv/CodingTheory/Dual.lean`, transcribed from

* F. J. MacWilliams and N. J. A. Sloane,
  *The Theory of Error-Correcting Codes*, North-Holland, Amsterdam, 1977.

It implements the *next sub-step* flagged in `CODING_THEORY_DIRECTIONS.md` after
the dual code: the explicit **generator/parity-check matrix duality** — a code
viewed as the *row space* of a generator matrix `G` and, dually, as the *kernel*
(solution space) of a parity-check matrix `H` (MacWilliams–Sloane, Ch. 1, §2 and
§8).

We keep the conventions of the foundational modules: a word lives in `ι → F` with
`[Fintype ι] [Field F]`, and a linear code is a subspace `C : Submodule F (ι → F)`
of length `n = #ι` (`codeLength`) and dimension `k = dim C` (`codeDim`).

## Main definitions

* `genCode G` — the code **generated** by a matrix `G : Matrix (Fin k) ι F`,
  i.e. the span of its rows (the book's "row space of the generator matrix").
* `parityCheckCode H` — the code **cut out** by a parity-check matrix
  `H : Matrix (Fin m) ι F`, i.e. the solution space `{x | H · x = 0}` (the kernel
  of `H.mulVecLin`).

## Main results

* `mem_parityCheckCode_iff` — membership of `parityCheckCode H` unfolded to the
  parity-check equations `∑ j, H i j * x j = 0`.
* `dualCode_genCode` — `(genCode G)ᗮ = parityCheckCode G`: the dual of the code
  generated by `G` is the code whose parity-check matrix is `G`.
* `dualCode_parityCheckCode` — `(parityCheckCode H)ᗮ = genCode H`: dually, the
  rows of a parity-check matrix generate the dual code.
* `codeDim_genCode` — `dim (genCode G) = rank Gᵀ` (the row rank).
* `codeDim_parityCheckCode` — `dim (parityCheckCode H) = n - rank H` (rank–nullity).
* `eq_parityCheckCode_iff_dualCode_eq_genCode` — `H` is a parity-check matrix for
  `C` iff its rows generate `Cᗮ`.

## References

* MacWilliams–Sloane, *The Theory of Error-Correcting Codes*, Ch. 1, §2 and §8.
-/

namespace CodingTheory

open scoped Classical
open Matrix

variable {ι : Type*} [Fintype ι] {F : Type*} [Field F] {k m : ℕ}

/-- The code **generated** by a matrix `G : Matrix (Fin k) ι F`: the `F`-span of
its rows.  This is the book's description of a code as the row space of a
generator matrix. -/
def genCode (G : Matrix (Fin k) ι F) : Submodule F (ι → F) :=
  Submodule.span F (Set.range G)

/-- The code **cut out** by a parity-check matrix `H : Matrix (Fin m) ι F`: the
solution space of the homogeneous system `H · x = 0`, i.e. the kernel of
`H.mulVecLin`. -/
noncomputable def parityCheckCode (H : Matrix (Fin m) ι F) : Submodule F (ι → F) :=
  LinearMap.ker H.mulVecLin

omit [Fintype ι] in
/-- A row of `G` lies in the generated code. -/
theorem row_mem_genCode (G : Matrix (Fin k) ι F) (i : Fin k) : G i ∈ genCode G :=
  Submodule.subset_span ⟨i, rfl⟩

/-- A word lies in the parity-check code iff it satisfies every parity-check
equation `∑ j, H i j * x j = 0`. -/
theorem mem_parityCheckCode_iff {H : Matrix (Fin m) ι F} {x : ι → F} :
    x ∈ parityCheckCode H ↔ ∀ i, ∑ j, H i j * x j = 0 := by
  unfold parityCheckCode
  rw [LinearMap.mem_ker, funext_iff]
  refine forall_congr' fun i => ?_
  simp [Matrix.mulVec, dotProduct]

/-- **Generator/parity-check duality.** The dual of the code generated by `G` is
the parity-check code of `G`: `(genCode G)ᗮ = parityCheckCode G`. -/
theorem dualCode_genCode (G : Matrix (Fin k) ι F) :
    dualCode (genCode G) = parityCheckCode G := by
  ext y
  rw [mem_dualCode_iff, mem_parityCheckCode_iff, genCode]
  constructor
  · intro h i
    have hmem : G i ∈ Submodule.span F (Set.range G) := Submodule.subset_span ⟨i, rfl⟩
    simpa [mul_comm] using h _ hmem
  · intro h c hc
    induction hc using Submodule.span_induction with
    | mem x hx =>
        obtain ⟨i, rfl⟩ := hx
        simpa [mul_comm] using h i
    | zero => simp
    | add a b _ _ iha ihb => simp [add_mul, Finset.sum_add_distrib, iha, ihb]
    | smul t a _ iha => simp [mul_assoc, ← Finset.mul_sum, iha]

/-- **Generator/parity-check duality (dual form).** The rows of a parity-check
matrix `H` generate the dual code: `(parityCheckCode H)ᗮ = genCode H`. -/
theorem dualCode_parityCheckCode (H : Matrix (Fin m) ι F) :
    dualCode (parityCheckCode H) = genCode H := by
  rw [← dualCode_genCode H, dualCode_dualCode]

omit [Fintype ι] in
/-- The dimension of a generated code is the row rank of `G` (the rank of its
transpose). -/
theorem codeDim_genCode (G : Matrix (Fin k) ι F) :
    codeDim (genCode G) = G.transpose.rank := by
  rw [codeDim, genCode, Matrix.rank, Matrix.range_mulVecLin]
  congr 1

/-- **Rank–nullity for a parity-check code.** The dimension of the code cut out by
`H` is `n - rank H`. -/
theorem codeDim_parityCheckCode (H : Matrix (Fin m) ι F) :
    codeDim (parityCheckCode H) = codeLength (parityCheckCode H) - H.rank := by
  have hrn := LinearMap.finrank_range_add_finrank_ker H.mulVecLin
  rw [codeDim, parityCheckCode, codeLength, Matrix.rank, Module.finrank_pi] at *
  omega

/-- `H` is a parity-check matrix for `C` (i.e. `C = parityCheckCode H`) exactly
when the rows of `H` generate the dual code `Cᗮ`. -/
theorem eq_parityCheckCode_iff_dualCode_eq_genCode
    (C : Submodule F (ι → F)) (H : Matrix (Fin m) ι F) :
    C = parityCheckCode H ↔ dualCode C = genCode H := by
  constructor
  · rintro rfl; rw [dualCode_parityCheckCode]
  · intro h
    rw [← dualCode_dualCode C, h]; exact dualCode_genCode H

end CodingTheory
