import Mathlib
import CodeTheoryCryptoEquiv.DiffUniformity.DifferentialUniformityUpstream

/-!
# EA-equivalence invariants of differential uniformity (the affine core of CCZ)

Two functions `F, G : 𝔽 → 𝔽` are **CCZ-equivalent** (Carlet–Charpin–Zinoviev,
1998) when the graph `{(x, F x)}` is mapped onto `{(x, G x)}` by an affine
permutation of `𝔽 × 𝔽`.  Differential uniformity, APN-ness and AB-ness are
CCZ-invariants, so every per-map result transports along the equivalence — the
unifying abstraction flagged as the highest-citation-leverage item in
`RESEARCH_DIRECTIONS.md`.

This file establishes the **EA-equivalence** (extended-affine) invariants, which
generate the affine core of CCZ-equivalence, in the characteristic-free `APN`
framework.  EA-equivalence is generated by three moves; together with the
post-composition invariance already proved in
`DifferentialUniformityUpstream.lean`
(`APN.differentialUniformity_comp_addEquiv`) they are:

* **pre-composition** with a domain automorphism `σ : V ≃+ V`
  (`differentialUniformity_precomp_addEquiv`);
* **addition of an additive map** `L : V →+ W`
  (`differentialUniformity_add_addMonoidHom`);
* post-composition with `σ : W ≃+ W` (already in the framework).

We also record the **graph reformulation** that full CCZ-equivalence is built on:
the differential count along a direction `(a, b)` of the graph of `f` is exactly
`fiberCard f a b` (`graphDiffCount_eq_fiberCard`), so the differential spectrum is
a property of the graph as a subset of `V × W`.

Building on that, the final section establishes **full graph-level
CCZ-equivalence**: if the graph of `g` is the image of the graph of `f` under an
affine permutation `z ↦ A z + t` of `V × W`, then `f` and `g` have the same
differential uniformity (and hence APN- and PN-ness are preserved).  This is the
classical Carlet–Charpin–Zinoviev invariance, here over commutative groups
`V`, `W`.

## Main results

* `fiberCard_precomp_addEquiv`, `differentialUniformity_precomp_addEquiv`.
* `fiberCard_add_addMonoidHom`, `differentialUniformity_add_addMonoidHom`.
* `IsAPN.precomp_addEquiv`, `IsAPN.add_addMonoidHom` (and the `IsPN` analogues).
* `differentialUniformity_ea` — **differential uniformity is an EA-invariant**:
  the general extended-affine image `x ↦ σ (f (τ x)) + L x` has the same
  differential uniformity as `f`, with the `IsAPN.ea` / `IsPN.ea` corollaries.
* `graphDiffCount_eq_fiberCard` — the graph reformulation underlying CCZ.
* `graphDiffCount_affine` — the graph-affine-permutation relation: the affine
  permutation `z ↦ A z + t` carries the differential count along `δ` to the count
  along `A δ`.
* `differentialUniformity_ccz` — **differential uniformity is a CCZ-invariant**,
  with the `IsAPN.ccz` / `IsPN.ccz` corollaries.
-/

open Finset

namespace APN

/-! ### Pre-composition with a domain automorphism -/

section Precomp
variable {V W : Type*} [AddGroup V] [Sub W] [Fintype V]

omit [Fintype V] in
/--
The derivative of `f ∘ σ` in direction `a` at `x` is the derivative of `f` in
direction `σ a` at `σ x`.
-/
lemma derivMap_precomp_addEquiv (f : V → W) (σ : V ≃+ V) (a x : V) :
    derivMap (f ∘ σ) a x = derivMap f (σ a) (σ x) := by
  simp +decide [ derivMap, Function.comp ]

omit [Fintype V] in
/--
Pre-composition with a domain automorphism `σ` re-indexes the fibres:
`fiberCard (f ∘ σ) a b = fiberCard f (σ a) b`.
-/
lemma fiberCard_precomp_addEquiv (f : V → W) (σ : V ≃+ V) (a : V) (b : W) :
    fiberCard (f ∘ σ) a b = fiberCard f (σ a) b := by
  fapply Nat.card_congr;
  refine' ( Equiv.subtypeEquiv σ.toEquiv _ );
  simp +decide [ derivMap_precomp_addEquiv ]

/--
Differential uniformity is invariant under pre-composition with an additive
equivalence of the domain.
-/
lemma differentialUniformity_precomp_addEquiv (f : V → W) (σ : V ≃+ V) :
    differentialUniformity (f ∘ σ) = differentialUniformity f := by
  refine' le_antisymm ( diffUnif_le_iff _ _ |>.2 _ ) ( diffUnif_le_iff _ _ |>.2 _ );
  · intro a ha b
    have h := fiberCard_precomp_addEquiv f σ a b
    have h' := fiberCard_le_diffUnif f (by
    exact fun h => ha ( σ.injective <| by simpa using h ) : σ a ≠ 0) b
    aesop;
  · intro a ha b;
    convert fiberCard_le_diffUnif ( f ∘ σ ) _ _ using 1;
    convert fiberCard_precomp_addEquiv f σ ( σ.symm a ) b |> Eq.symm using 1;
    · rw [ σ.apply_symm_apply ];
    · aesop

end Precomp

/-! ### Adding an additive map -/

section AddHom
variable {V W : Type*} [AddGroup V] [AddCommGroup W] [Fintype V]

omit [Fintype V] in
/--
The derivative of `x ↦ f x + L x` (for an additive `L`) in direction `a` is the
derivative of `f` shifted by the constant `L a`.
-/
lemma derivMap_add_addMonoidHom (f : V → W) (L : V →+ W) (a x : V) :
    derivMap (fun x => f x + L x) a x = derivMap f a x + L a := by
  unfold derivMap; simp +decide [ add_sub_add_comm ] ;

omit [Fintype V] in
/--
Adding an additive map `L` only shifts the target value of each fibre:
`fiberCard (f + L) a b = fiberCard f a (b - L a)`.
-/
lemma fiberCard_add_addMonoidHom (f : V → W) (L : V →+ W) (a : V) (b : W) :
    fiberCard (fun x => f x + L x) a b = fiberCard f a (b - L a) := by
  unfold fiberCard;
  rw [ show derivMap ( fun x => f x + L x ) a = fun x => derivMap f a x + L a from funext fun x => derivMap_add_addMonoidHom f L a x ];
  congr with x ; simp +decide [ eq_sub_iff_add_eq ]

/--
Differential uniformity is invariant under adding an additive map.
-/
lemma differentialUniformity_add_addMonoidHom (f : V → W) (L : V →+ W) :
    differentialUniformity (fun x => f x + L x) = differentialUniformity f := by
  refine' le_antisymm _ _;
  · refine' diffUnif_le_iff _ _ |>.2 fun a ha b => _;
    exact fiberCard_add_addMonoidHom f L a b ▸ fiberCard_le_diffUnif f ha ( b - L a );
  · refine' diffUnif_le_iff f _ |>.2 fun a ha b => _;
    convert fiberCard_le_diffUnif ( fun x => f x + L x ) ha ( b + L a ) using 1 ; simp +decide [ fiberCard_add_addMonoidHom ]

end AddHom

/-! ### EA-invariance corollaries for APN / PN -/

section Corollaries
variable {V W : Type*} [AddGroup V] [AddCommGroup W] [Fintype V]

theorem IsAPN.precomp_addEquiv {f : V → W} (hf : IsAPN f) (σ : V ≃+ V) :
    IsAPN (f ∘ σ) := by
  unfold IsAPN at *; rw [differentialUniformity_precomp_addEquiv]; exact hf

theorem IsPN.precomp_addEquiv {f : V → W} (hf : IsPN f) (σ : V ≃+ V) :
    IsPN (f ∘ σ) := by
  unfold IsPN at *; rw [differentialUniformity_precomp_addEquiv]; exact hf

theorem IsAPN.add_addMonoidHom {f : V → W} (hf : IsAPN f) (L : V →+ W) :
    IsAPN (fun x => f x + L x) := by
  unfold IsAPN at *; rw [differentialUniformity_add_addMonoidHom]; exact hf

theorem IsPN.add_addMonoidHom {f : V → W} (hf : IsPN f) (L : V →+ W) :
    IsPN (fun x => f x + L x) := by
  unfold IsPN at *; rw [differentialUniformity_add_addMonoidHom]; exact hf

end Corollaries

/-! ### The extended-affine (EA) equivalence capstone -/

section EA
variable {V W W' : Type*} [AddGroup V] [AddCommGroup W] [AddCommGroup W'] [Fintype V]

/--
**Differential uniformity is an EA-invariant.**  Extended-affine equivalence is
generated by the three moves recorded above (pre-composition with a domain
automorphism `τ`, post-composition with a codomain automorphism `σ`, and addition
of an additive map `L`); composing them shows that the most general
extended-affine image `x ↦ σ (f (τ x)) + L x` has the same differential
uniformity as `f`.
-/
theorem differentialUniformity_ea (f : V → W) (τ : V ≃+ V) (σ : W ≃+ W')
    (L : V →+ W') :
    differentialUniformity (fun x => σ (f (τ x)) + L x) = differentialUniformity f := by
  rw [differentialUniformity_add_addMonoidHom (fun x => σ (f (τ x))) L,
    show (fun x => σ (f (τ x))) = (σ ∘ (f ∘ τ)) from rfl,
    differentialUniformity_comp_addEquiv (f ∘ τ) σ,
    differentialUniformity_precomp_addEquiv f τ]

/-- **APN-ness is an EA-invariant.**  The extended-affine image
`x ↦ σ (f (τ x)) + L x` of an APN map is APN. -/
theorem IsAPN.ea {f : V → W} (hf : IsAPN f) (τ : V ≃+ V) (σ : W ≃+ W')
    (L : V →+ W') : IsAPN (fun x => σ (f (τ x)) + L x) := by
  unfold IsAPN at *; rw [differentialUniformity_ea]; exact hf

/-- **PN-ness is an EA-invariant.**  The extended-affine image
`x ↦ σ (f (τ x)) + L x` of a PN (planar) map is PN. -/
theorem IsPN.ea {f : V → W} (hf : IsPN f) (τ : V ≃+ V) (σ : W ≃+ W')
    (L : V →+ W') : IsPN (fun x => σ (f (τ x)) + L x) := by
  unfold IsPN at *; rw [differentialUniformity_ea]; exact hf

end EA

/-! ### The graph reformulation underlying CCZ-equivalence -/

section Graph
variable {V W : Type*} [AddGroup V] [AddCommGroup W] [Fintype V]

/-- The graph of `f` as a subset of `V × W`. -/
def graph (f : V → W) : Set (V × W) := {z | z.2 = f z.1}

/-- The number of graph points `z` with `z + δ` again on the graph, for a
direction `δ = (a, b)`.  This is the count that an affine automorphism of `V × W`
preserves, hence the object on which CCZ-equivalence acts. -/
noncomputable def graphDiffCount (f : V → W) (δ : V × W) : ℕ :=
  Nat.card {z : V × W // z ∈ graph f ∧ z + δ ∈ graph f}

omit [Fintype V] in
/--
**Graph reformulation.** The graph differential count along direction `(a, b)`
equals the derivative fibre count `fiberCard f a b`.  Thus the differential
spectrum of `f` is a property of its graph, which is what makes it a
CCZ-invariant.
-/
theorem graphDiffCount_eq_fiberCard (f : V → W) (a : V) (b : W) :
    graphDiffCount f (a, b) = fiberCard f a b := by
  fapply Nat.card_congr;
  refine' Equiv.ofBijective ( fun x => ⟨ x.val.1, _ ⟩ ) ⟨ fun x y h => _, fun x => _ ⟩;
  all_goals simp_all +decide [ graph, derivMap ];
  any_goals cases x; simp_all +decide [ graph ];
  · rename_i x hx; rcases hx with ⟨ hx₁, hx₂ ⟩ ; simp_all +decide [ graph ] ;
    rw [ ← hx₂, add_sub_cancel_left ];
  · unfold graph at *; aesop;
  · unfold derivMap at *; aesop;

end Graph

/-! ### Full graph-level CCZ-equivalence -/

section CCZ
variable {V W : Type*} [AddCommGroup V] [AddCommGroup W]

/--
**Graph-affine-permutation relation.**  Suppose the graph of `g` is the image of
the graph of `f` under the affine permutation `z ↦ A z + t` of `V × W` (`A` an
additive automorphism, `t` a translation).  Then the graph differential count of
`g` along the direction `A δ` equals that of `f` along `δ`.

This is the heart of CCZ-equivalence: the affine map carries the pairs of graph
points that realise a differential along `δ` to the pairs realising the
differential along `A δ`.
-/

/-
Under the affine-image hypothesis, the point `A w + t` lies on the graph of `g`
exactly when `w` lies on the graph of `f` (using injectivity of `A` and of
translation by `t`).
-/
lemma mem_graph_affine_iff (f g : V → W) (A : (V × W) ≃+ (V × W)) (t : V × W)
    (hgf : graph g = (fun z => A z + t) '' graph f) (w : V × W) :
    (A w + t) ∈ graph g ↔ w ∈ graph f := by
  simp +decide [ hgf, Set.mem_image ]

theorem graphDiffCount_affine (f g : V → W) (A : (V × W) ≃+ (V × W)) (t : V × W)
    (hgf : graph g = (fun z => A z + t) '' graph f) (δ : V × W) :
    graphDiffCount g (A δ) = graphDiffCount f δ := by
  unfold graphDiffCount
  apply Nat.card_congr
  refine (Equiv.subtypeEquiv (A.toEquiv.trans (Equiv.addRight t)) ?_).symm
  intro z
  have h2 : (A z + t) + A δ = A (z + δ) + t := by rw [map_add]; abel
  simp only [Equiv.trans_apply, AddEquiv.toEquiv_eq_coe, EquivLike.coe_coe,
    Equiv.coe_addRight]
  rw [mem_graph_affine_iff f g A t hgf z, h2, mem_graph_affine_iff f g A t hgf (z + δ)]

/-
The affine permutation maps the zero direction to the zero direction, so a
nonzero direction stays nonzero.
-/
lemma fiberCard_fst_zero (f : V → W) {b : W} (hb : b ≠ 0) :
    fiberCard f 0 b = 0 := by
  convert Nat.card_eq_zero.mpr ?_;
  exact Or.inl ⟨ by rintro ⟨ x, hx ⟩ ; exact hb ( by simpa [ derivMap ] using hx.symm ) ⟩

variable [Fintype V] [Fintype W]

/--
**Differential uniformity is a CCZ-invariant.**  If the graph of `g` is the
affine image (`z ↦ A z + t`) of the graph of `f`, then `f` and `g` have the same
differential uniformity.
-/

/-
One direction of CCZ-invariance: the differential uniformity of the affine image
is bounded by that of the original.
-/
lemma differentialUniformity_ccz_le (f g : V → W) (A : (V × W) ≃+ (V × W)) (t : V × W)
    (hgf : graph g = (fun z => A z + t) '' graph f) :
    differentialUniformity g ≤ differentialUniformity f := by
  refine' diffUnif_le_iff g _ |>.2 fun a ha b => _;
  -- Set `δ := A.symm (a, b)`, so `A δ = (a, b)`.
  set δ : V × W := A.symm (a, b);
  -- Then by `graphDiffCount_affine`, `graphDiffCount g (a, b) = graphDiffCount g (A δ) = graphDiffCount f δ`, and by `graphDiffCount_eq_fiberCard` again `graphDiffCount f δ = fiberCard f δ.1 δ.2`.
  have h_diff_unif : fiberCard g a b = fiberCard f δ.1 δ.2 := by
    convert graphDiffCount_affine f g A t hgf δ using 1;
    · rw [ show A δ = ( a, b ) from A.apply_symm_apply ( a, b ) ] ; exact graphDiffCount_eq_fiberCard g a b ▸ rfl;
    · exact graphDiffCount_eq_fiberCard f δ.1 δ.2 ▸ rfl;
  by_cases hδ : δ.1 = 0;
  · by_cases hδ' : δ.2 = 0 <;> simp_all +decide [ fiberCard_fst_zero ];
    exact absurd ( A.symm.injective ( show A.symm ( a, b ) = A.symm 0 by ext <;> aesop ) ) ( by aesop );
  · exact h_diff_unif ▸ fiberCard_le_diffUnif f hδ _

theorem differentialUniformity_ccz (f g : V → W) (A : (V × W) ≃+ (V × W)) (t : V × W)
    (hgf : graph g = (fun z => A z + t) '' graph f) :
    differentialUniformity g = differentialUniformity f := by
  refine' le_antisymm ( differentialUniformity_ccz_le f g A t hgf ) ( differentialUniformity_ccz_le g f A.symm ( -A.symm t ) _ );
  refine' Set.Subset.antisymm _ _;
  · intro x hx; use A x + t; simp_all +decide [ graph ] ;
  · simp +decide [ Set.image_subset_iff, hgf ];
    simp +decide [ Set.subset_def, graph ]

/-- APN-ness is a CCZ-invariant. -/
theorem IsAPN.ccz {f g : V → W} (hf : IsAPN f) (A : (V × W) ≃+ (V × W)) (t : V × W)
    (hgf : graph g = (fun z => A z + t) '' graph f) : IsAPN g := by
  unfold IsAPN at *; rw [differentialUniformity_ccz f g A t hgf]; exact hf

/-- PN-ness is a CCZ-invariant. -/
theorem IsPN.ccz {f g : V → W} (hf : IsPN f) (A : (V × W) ≃+ (V × W)) (t : V × W)
    (hgf : graph g = (fun z => A z + t) '' graph f) : IsPN g := by
  unfold IsPN at *; rw [differentialUniformity_ccz f g A t hgf]; exact hf

end CCZ

end APN