/-
Copyright (c) 2026 The mathlib4 community / Harmonic. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: (to be completed by submitter)
-/
import CodeTheoryCryptoEquiv.Upstream.Dual

/-!
# Generator and parity-check matrices

> Intended Mathlib target path: this extends the linear-code file
> (`Mathlib/InformationTheory/LinearCode.lean`, cf. `Upstream/LinearCode.lean`
> and `Upstream/Dual.lean`).
>
> For the actual pull request the blanket `import Mathlib` pulled in via
> `Upstream.Dual` should be minimised (e.g. with `shake`).

This file makes precise the two complementary matrix descriptions of a linear
code: as the **row space** of a generator matrix `G`, and as the **kernel**
(solution space) of a parity-check matrix `H`.  The bridge between them is the
dual code from `Upstream/Dual.lean`: the dual of the code generated by `G` is the
code cut out by `G`, and dually the rows of a parity-check matrix generate the
dual code.

## Main definitions

* `LinearCode.gen G` — the code generated by `G : Matrix (Fin k) ι F`, i.e. the
  span of its rows.
* `LinearCode.parityCheck H` — the code cut out by `H : Matrix (Fin m) ι F`, i.e.
  the kernel of `H.mulVecLin`.

## Main results

* `LinearCode.mem_parityCheck_iff` — membership unfolded to the parity-check
  equations.
* `LinearCode.dual_gen` — `(gen G)ᗮ = parityCheck G`.
* `LinearCode.dual_parityCheck` — `(parityCheck H)ᗮ = gen H`.
* `LinearCode.dim_gen` — `dim (gen G) = rank Gᵀ`.
* `LinearCode.dim_parityCheck` — `dim (parityCheck H) = n - rank H`.
* `LinearCode.eq_parityCheck_iff_dual_eq_gen` — `H` is a parity-check matrix for
  `C` iff its rows generate `Cᗮ`.

## References

* F. J. MacWilliams and N. J. A. Sloane, *The Theory of Error-Correcting Codes*,
  North-Holland, Amsterdam, 1977. (Ch. 1, §2 and §8.)

## Tags

linear code, generator matrix, parity-check matrix, row space, dual code
-/

open scoped Classical

namespace LinearCode

open Matrix

variable {ι : Type*} [Fintype ι] {F : Type*} [Field F] {k m : ℕ}

/-- The code **generated** by a matrix `G : Matrix (Fin k) ι F`: the `F`-span of
its rows (the row space of the generator matrix). -/
def gen (G : Matrix (Fin k) ι F) : LinearCode ι F :=
  Submodule.span F (Set.range G)

/-- The code **cut out** by a parity-check matrix `H : Matrix (Fin m) ι F`: the
solution space of `H · x = 0`, i.e. the kernel of `H.mulVecLin`. -/
def parityCheck (H : Matrix (Fin m) ι F) : LinearCode ι F :=
  LinearMap.ker H.mulVecLin

/-- A row of `G` lies in the generated code. -/
theorem row_mem_gen (G : Matrix (Fin k) ι F) (i : Fin k) : G i ∈ gen G :=
  Submodule.subset_span ⟨i, rfl⟩

/-- A word lies in the parity-check code iff it satisfies every parity-check
equation `∑ j, H i j * x j = 0`. -/
theorem mem_parityCheck_iff {H : Matrix (Fin m) ι F} {x : ι → F} :
    x ∈ parityCheck H ↔ ∀ i, ∑ j, H i j * x j = 0 := by
  unfold parityCheck
  rw [LinearMap.mem_ker, funext_iff]
  refine forall_congr' fun i => ?_
  simp [Matrix.mulVec, dotProduct]

/-- **Generator/parity-check duality.** The dual of the code generated by `G` is
the parity-check code of `G`. -/
theorem dual_gen (G : Matrix (Fin k) ι F) : dual (gen G) = parityCheck G := by
  ext y
  rw [mem_dual_iff, mem_parityCheck_iff, gen]
  constructor
  · intro h i
    have hmem : G i ∈ Submodule.span F (Set.range G) := Submodule.subset_span ⟨i, rfl⟩
    simpa [mul_comm] using h _ hmem
  · intro h c hc
    induction hc using Submodule.span_induction with
    | mem x hx =>
        obtain ⟨i, rfl⟩ := hx
        simpa [mul_comm] using h i
    | zero => simp
    | add a b _ _ iha ihb => simp [add_mul, Finset.sum_add_distrib, iha, ihb]
    | smul t a _ iha => simp [mul_assoc, ← Finset.mul_sum, iha]

/-- **Generator/parity-check duality (dual form).** The rows of a parity-check
matrix generate the dual code. -/
theorem dual_parityCheck (H : Matrix (Fin m) ι F) : dual (parityCheck H) = gen H := by
  rw [← dual_gen H, dual_dual]

/-- The dimension of a generated code is the row rank of `G` (the rank of its
transpose). -/
theorem dim_gen (G : Matrix (Fin k) ι F) : (gen G).dim = G.transpose.rank := by
  rw [dim_eq_finrank, gen, Matrix.rank, Matrix.range_mulVecLin]
  congr 1

/-- **Rank–nullity for a parity-check code.** The dimension of the code cut out by
`H` is `n - rank H`. -/
theorem dim_parityCheck (H : Matrix (Fin m) ι F) :
    (parityCheck H).dim = (parityCheck H).length - H.rank := by
  have hrn := LinearMap.finrank_range_add_finrank_ker H.mulVecLin
  rw [dim_eq_finrank, parityCheck, length_eq_card, Matrix.rank, Module.finrank_pi] at *
  omega

/-- `H` is a parity-check matrix for `C` (i.e. `C = parityCheck H`) exactly when
the rows of `H` generate the dual code `Cᗮ`. -/
theorem eq_parityCheck_iff_dual_eq_gen (C : LinearCode ι F) (H : Matrix (Fin m) ι F) :
    C = parityCheck H ↔ dual C = gen H := by
  constructor
  · rintro rfl; rw [dual_parityCheck]
  · intro h
    rw [← dual_dual C, h]; exact dual_gen H

end LinearCode
