import Mathlib
import DobbertinLego.Endo
import DobbertinLego.Frobenius
import DobbertinLego.Loop
import DobbertinLego.Assembly

/-!
# Categorical patterns behind the LEGO bricks

This layer traces every component of the step `(1) ⟹ (2)` of Dobbertin's
Theorem 1 back to its most abstract categorical / algebraic foundation, using
Mathlib's `CategoryTheory` vocabulary.  Nothing here is needed to *prove* the
headline (that is done in `DobbertinLego.lean`); this file only makes the
structure the discussion identified *visible* as honest Lean statements.

The dictionary it formalises:

| paper component          | categorical foundation                                   |
|--------------------------|----------------------------------------------------------|
| Frobenius `frob` (shift) | a **monoid action** `Multiplicative ℕ →* End`, i.e. a functor `SingleObj (Multiplicative ℕ) ⥤ C` (the delooping `Bℕ`) |
| loop / trace `iterSum`   | the **norm element** `∑ φⁱ`, built by the **NNO / initial-algebra recursor** on `ℕ` |
| telescope (Artin–Schreier)| multiplication by the **augmentation** `φ − 1` in the endomorphism **ring** `End A` (geometric series) |
| trace as a **bit**       | the **finite order** `φⁿ = 1` (cyclic Galois group) forcing the norm element into the fixed subobject |
| absolute trace `Tr`      | the **categorical trace** (eval/coeval loop) = Mathlib's `Algebra.trace 𝔽₂ F` |
| char 2                   | the irreducible *input* making `φ` an **endomorphism of the additive group** at all |

Each row below is a theorem.
-/

namespace Dobbertin.Lego

open CategoryTheory Finset

/-! ## 1. Frobenius = the *shift* = an ℕ-action (monoid delooping)

The Frobenius is not a bare set map: additivity (`frob_add`) makes each iterate an
endomorphism of the additive group, and composition (`frob_comp`) makes the family
`r ↦ frobEndo r` a **monoid homomorphism** out of `Multiplicative ℕ` — the free
monoid on one generator (the "shift").  This is the ℕ-action underlying the whole
development. -/

section Action

variable {F : Type*} [Field F] [Fintype F] [CharP F 2]

/-- **Frobenius as an ℕ-action.**  The monoid homomorphism
`Multiplicative ℕ →* AddMonoid.End F`, `r ↦ frobEndo r`, sending the additive
generator `1` to a single Frobenius step.  `map_one` is `frob 0 = id`; `map_mul`
is `frob (a+b) = frob a ∘ frob b`.  This packages "Frobenius is the shift" as a
monoid action on the additive group `F`. -/
noncomputable def frobAction : Multiplicative ℕ →* AddMonoid.End F where
  toFun r := frobEndo (F := F) (Multiplicative.toAdd r)
  map_one' := AddMonoidHom.ext fun x => by show frob 0 x = x; simp [frob]
  map_mul' a b := AddMonoidHom.ext fun x => by
    show frob (Multiplicative.toAdd a + Multiplicative.toAdd b) x = frob _ (frob _ x)
    simp only [frob]; rw [← pow_mul, ← pow_add]; ring_nf

omit [Fintype F] in
@[simp] lemma frobAction_apply (r : Multiplicative ℕ) (x : F) :
    frobAction r x = frob (Multiplicative.toAdd r) x := rfl

/-- The same action, valued in the plain endomorphism monoid `End F` of the object
`F` in the category of types.  This is the data of a functor out of the
single-object category `SingleObj (Multiplicative ℕ) = Bℕ`. -/
def frobTypeHom : Multiplicative ℕ →* CategoryTheory.End (F : Type _) where
  toFun r := frob (F := F) (Multiplicative.toAdd r)
  map_one' := funext fun x => by show frob 0 x = x; simp [frob]
  map_mul' a b := funext fun x => by
    show frob (Multiplicative.toAdd a + Multiplicative.toAdd b) x = frob _ (frob _ x)
    simp only [frob]; rw [← pow_mul, ← pow_add]; ring_nf

/-- **The Frobenius delooping functor** `Bℕ ⥤ Type`.  The single-object category
`SingleObj (Multiplicative ℕ)` (the one-object groupoid-shaped delooping of the
monoid `ℕ`) maps to `Type`, sending the unique object to `F` and each morphism `r`
to the Frobenius `frob r`.  A functor out of `SingleObj M` is *exactly* a monoid
action of `M`, so this is the category-theoretic incarnation of "Frobenius is an
ℕ-action". -/
noncomputable def frobFunctor : SingleObj (Multiplicative ℕ) ⥤ Type _ :=
  SingleObj.functor (frobTypeHom (F := F))

omit [Fintype F] [CharP F 2] in
/-- The delooping functor sends the morphism `r` to the Frobenius map `frob r`. -/
lemma frobFunctor_map (r : Multiplicative ℕ) (x : F) :
    (frobFunctor (F := F)).map (X := SingleObj.star _) (Y := SingleObj.star _) r x
      = frob (Multiplicative.toAdd r) x := rfl

end Action

/-! ## 2. The loop / trace = norm element built by the NNO recursor

The loop `iterSum φ len = ∑_{i<len} φⁱ` is generated by the inductive/`Nat.rec`
pattern: it is the unique function on `ℕ` with `h 0 = 0` and
`h (len+1) = h len + φ^len x`.  This universal property is precisely the recursor
of a natural-number object (initial algebra of `X ↦ 1 + X`); Mathlib has no NNO
class, so we record the property directly. -/

section NNO

variable {A : Type*} [AddCommGroup A]

/-- **NNO recursor / uniqueness for the norm element.**  Any function `g : ℕ → A`
satisfying the two structural equations `g 0 = 0` and
`g (len+1) = g len + (φ^len) x` coincides with `iterSum φ · x`.  This is the
universal property of `ℕ` as a natural-number object (initial `1 + (−)`-algebra),
of which `iterSum` is an instance. -/
theorem iterSum_rec_unique (φ : AddMonoid.End A) (x : A) (g : ℕ → A)
    (h0 : g 0 = 0) (hs : ∀ len, g (len + 1) = g len + (φ ^ len) x) :
    ∀ len, g len = iterSum φ len x := by
  intro len
  induction len with
  | zero => simpa using h0
  | succ m ih => rw [hs, ih, iterSum_succ]

end NNO

/-! ## 3. The telescope = the augmentation `φ − 1` in the endomorphism ring

Both telescoping identities are one algebraic fact: in the (non-commutative)
endomorphism **ring** `AddMonoid.End A`, the norm element `∑ φⁱ` times the
**augmentation** `φ − 1` is `φ^len − 1` — the geometric series.  Applying this to
`x` recovers the pointwise `iterSum_telescope`. -/

section Ring

variable {A : Type*} [AddCommGroup A]

/-- **The norm element as a ring element.**  `normElt φ len = ∑_{i<len} φⁱ` lives
in the endomorphism ring `AddMonoid.End A` (multiplication = composition). -/
def normElt (φ : AddMonoid.End A) (len : ℕ) : AddMonoid.End A := ∑ i ∈ range len, φ ^ i

/-- Evaluating the ring-level norm element recovers the pointwise `iterSum`. -/
@[simp] lemma normElt_apply (φ : AddMonoid.End A) (len : ℕ) (x : A) :
    normElt φ len x = iterSum φ len x := by
  rw [normElt, iterSum]
  induction len with
  | zero => simp
  | succ m ih => rw [Finset.sum_range_succ, Finset.sum_range_succ, ← ih]; rfl

/-- **The telescope as an augmentation identity** (left form): in the endomorphism
ring, `(φ − 1) · (∑ φⁱ) = φ^len − 1`.  This is the geometric series `mul_geom_sum`;
the whole Artin–Schreier telescope is this ring identity applied to `x`. -/
theorem augmentation_mul_normElt (φ : AddMonoid.End A) (len : ℕ) :
    (φ - 1) * normElt φ len = φ ^ len - 1 := mul_geom_sum φ len

/-- **The telescope as an augmentation identity** (right form): `(∑ φⁱ) · (φ − 1) =
φ^len − 1`. -/
theorem normElt_mul_augmentation (φ : AddMonoid.End A) (len : ℕ) :
    normElt φ len * (φ - 1) = φ ^ len - 1 := geom_sum_mul φ len

end Ring

/-! ## 4. The absolute trace = the categorical (eval/coeval) trace

The absolute trace `Tr(x) = ∑_{i<n} x^{2^i}` is not an ad-hoc sum: it *is*
Mathlib's `Algebra.trace 𝔽₂ F`, the value of the categorical "open a loop with
coevaluation, insert multiplication-by-`x`, close it with evaluation" move.  Over
the prime field `𝔽₂ = ZMod 2`, Mathlib computes that trace as the Frobenius sum
`∑_{i<[F:𝔽₂]} x^{2^i}`, which is exactly the loop. -/

section Trace

variable {F : Type*} [Field F] [Fintype F] [CharP F 2]

/-- **The trace loop is the categorical/field trace.**  At full length
`n = [F : 𝔽₂]`, the paper's `trace n` equals Mathlib's `Algebra.trace (ZMod 2) F`
pushed back into `F` along `algebraMap` — the evaluation/coevaluation trace of the
multiplication endomorphisms of `F`. -/
theorem trace_eq_algebraMap_trace (x : F) :
    letI := ZMod.algebra F 2
    trace (Module.finrank (ZMod 2) F) x
      = algebraMap (ZMod 2) F (Algebra.trace (ZMod 2) F x) := by
  letI := ZMod.algebra F 2
  rw [FiniteField.algebraMap_trace_eq_sum_pow (ZMod 2) F x]
  unfold trace loop
  have hcard : Nat.card (ZMod 2) = 2 := by simp
  rw [hcard]
  refine Finset.sum_congr rfl (fun i _ => ?_)
  simp [frob]

end Trace

end Dobbertin.Lego
