import RequestProject.CodingTheory.MDS

/-!
# Finite geometry: arcs and MDS codes

This module is the **geometry** companion (`FUTURE_DIRECTIONS_FOUNDATIONS.md`,
T2.1) to the Singleton / MDS theory of
`RequestProject/CodingTheory/MDS.lean`.  It records the classical equivalence
between **MDS codes** and **arcs in projective space**.

A generator matrix `G : Matrix (Fin k) ι F` of a `[n, k]` code has its `n = #ι`
columns as points of the projective space `PG(k-1, q)` (vectors in `Fᵏ` up to
scalars).  An **`n`-arc** is a set of points in *general position*: every `k` of
them are linearly independent (no `k` lie on a hyperplane through the origin).
The theorem (MacWilliams–Sloane, Ch. 11, Thm 8; the geometric form of the
Singleton/MDS corollary, roadmap item 5) is:

> A code with generator matrix `G` whose rows are linearly independent is **MDS**
> iff its columns form an **arc**, i.e. every `k` columns are linearly
> independent.

The bridge is the information-set characterization already proved in
`MDS.lean` (`isMDS_iff_forall_disjoint_vanishing`): a `k`-subset `S` of
coordinates is an information set (`Disjoint C (vanishingOn S)`) exactly when the
`k` columns indexed by `S` are linearly independent (equivalently, span `Fᵏ`,
since the dot product is nondegenerate and `#S = k = dim Fᵏ`).

## Main definitions

* `arcColumn G i` — the `i`-th column of `G`, a point `fun r => G r i : Fin k → F`.
* `IsArc G` — every `k`-subset of columns of `G` is linearly independent
  (general position).

## Main results

* `codeDim_genCode_of_rows_li` — independent rows give a code of dimension `k`.
* `disjoint_vanishingOn_iff_columns_li` — the information-set ⇄ column-independence
  bridge.
* `isMDS_genCode_iff_isArc` — **arc ⇄ MDS**: for a generator matrix with
  independent rows, `genCode G` is MDS iff `G` is an arc.

## References

* MacWilliams–Sloane, *The Theory of Error-Correcting Codes*, Ch. 11, §3, Thm 8.
-/

namespace CodingTheory

open scoped Classical
open Matrix

variable {ι : Type*} [Fintype ι] {F : Type*} [Field F] {k : ℕ}

/-- The `i`-th **column** of a generator matrix `G`, viewed as a point of `Fᵏ`
(a representative of a point of `PG(k-1, q)`). -/
def arcColumn (G : Matrix (Fin k) ι F) (i : ι) : Fin k → F := fun r => G r i

/-- `G` is an **arc**: its columns are in *general position*, i.e. every
`k`-subset of columns is linearly independent. -/
def IsArc (G : Matrix (Fin k) ι F) : Prop :=
  ∀ S : Finset ι, S.card = k → LinearIndependent F (fun i : S => arcColumn G (i : ι))

omit [Fintype ι] in
/-- A generator matrix with linearly independent rows generates a code of
dimension `k`. -/
theorem codeDim_genCode_of_rows_li {G : Matrix (Fin k) ι F}
    (hG : LinearIndependent F G) : codeDim (genCode G) = k := by
  rw [codeDim, genCode, finrank_span_eq_card hG]
  simp

/-
For a matrix with equally many rows and columns, the rows are linearly
independent iff the columns are (both are equivalent to invertibility after
reindexing to a square matrix).
-/
theorem linearIndependent_row_iff_col {m n : Type*} [Fintype m] [Fintype n]
    [DecidableEq m] [DecidableEq n] (M : Matrix m n F)
    (hmn : Fintype.card n = Fintype.card m) :
    LinearIndependent F M.row ↔ LinearIndependent F M.col := by
  obtain ⟨e⟩ : Nonempty (n ≃ m) := by
    exact ⟨ Fintype.equivOfCardEq hmn ⟩;
  have h_equiv : LinearIndependent F M.row ↔ LinearIndependent F (fun i : m => M.row i ∘ e.symm) := by
    rw [ Fintype.linearIndependent_iff ];
    rw [ Fintype.linearIndependent_iff ];
    simp +decide [ funext_iff, Finset.sum_apply, Pi.smul_apply ];
    exact ⟨ fun h g hg i => h g ( fun x => by simpa using hg ( e x ) ) i, fun h g hg i => h g ( fun x => by simpa using hg ( e.symm x ) ) i ⟩;
  have h_equiv : LinearIndependent F (fun i : m => M.row i ∘ e.symm) ↔ IsUnit (Matrix.of (fun i j => M i (e.symm j))) := by
    convert Matrix.linearIndependent_rows_iff_isUnit ( A := Matrix.of ( fun i j => M i ( e.symm j ) ) ) using 1;
  convert h_equiv using 1;
  rw [ ← Matrix.linearIndependent_cols_iff_isUnit ];
  convert linearIndependent_equiv ( e.symm : m ≃ n ) |> Iff.symm using 1

omit [Fintype ι] in
/-- The code generated by `G` is the range of the row-combination map
`a ↦ a ᵥ* G`. -/
theorem genCode_eq_range_vecMulLinear (G : Matrix (Fin k) ι F) :
    genCode G = LinearMap.range G.vecMulLinear := by
  apply le_antisymm;
  · intro x hx
    simp [genCode] at hx;
    rw [ Submodule.mem_span_range_iff_exists_fun ] at hx;
    aesop;
  · rintro x ⟨ a, rfl ⟩;
    convert Submodule.sum_mem _ fun i ( hi : i ∈ Finset.univ ) => Submodule.smul_mem _ ( a i ) ( Submodule.subset_span ( Set.mem_range_self i ) ) using 1;
    ext j; simp +decide [ Matrix.vecMul, dotProduct ] ;

omit [Fintype ι] in
/-- **The information-set ⇄ column-independence bridge.**  For a generator matrix
with independent rows and a `k`-subset `S`, the coordinates `S` form an
information set (`Disjoint (genCode G) (vanishingOn S)`) iff the `k` columns
indexed by `S` are linearly independent. -/
theorem disjoint_vanishingOn_iff_columns_li {G : Matrix (Fin k) ι F}
    (hG : LinearIndependent F G) (S : Finset ι) (hS : S.card = k) :
    Disjoint (genCode G) (vanishingOn S)
      ↔ LinearIndependent F (fun i : S => arcColumn G (i : ι)) := by
  -- Let `P : Matrix (Fin k) {x // x ∈ S} F` be the submatrix with columns indexed by `S`.
  set P : Matrix (Fin k) S F := Matrix.of (fun r i => G r i);
  constructor <;> intro h_conj;
  · have h_inj : Function.Injective (fun a : Fin k → F => a ᵥ* P) := by
      intro a b hab;
      have h_eq : (a - b) ᵥ* G ∈ vanishingOn S := by
        simp_all +decide [ funext_iff, Matrix.vecMul, dotProduct ];
        simp_all +decide [ sub_mul ];
        exact fun i hi => sub_eq_zero_of_eq <| hab i hi;
      have h_eq_zero : (a - b) ᵥ* G = 0 := by
        have h_eq_zero : (a - b) ᵥ* G ∈ genCode G := by
          exact genCode_eq_range_vecMulLinear G ▸ LinearMap.mem_range_self _ _;
        exact h_conj.le_bot ⟨ h_eq_zero, h_eq ⟩;
      rw [ Fintype.linearIndependent_iff ] at hG;
      exact funext fun i => sub_eq_zero.mp ( hG ( a - b ) ( by simpa [ funext_iff ] using h_eq_zero ) i );
    have h_row_li : LinearIndependent F P.row := by
      convert Matrix.vecMul_injective_iff.mp h_inj using 1;
    convert linearIndependent_row_iff_col P _ |>.1 h_row_li using 1;
    simp +decide [ hS ];
  · -- By assumption, `P.col` is linearly independent, so `P.row` is also linearly independent by `linearIndependent_row_iff_col`.
    have hP_row : LinearIndependent F P.row := by
      convert linearIndependent_row_iff_col P ( by simp +decide [ hS ] ) |>.2 h_conj using 1;
    -- By definition of `genCode`, every element in `genCode G` is of the form `a ᵥ* G` for some `a : Fin k → F`.
    have h_genCode : ∀ c ∈ genCode G, ∃ a : Fin k → F, c = a ᵥ* G := by
      intro c hc
      rw [genCode_eq_range_vecMulLinear] at hc
      obtain ⟨a, ha⟩ := hc
      use a
      aesop;
    -- By assumption, `P.row` is linearly independent, so `a ᵥ* P = 0` implies `a = 0`.
    have hP_zero : ∀ a : Fin k → F, a ᵥ* P = 0 → a = 0 := by
      exact fun a ha => by simpa [ funext_iff ] using Fintype.linearIndependent_iff.mp hP_row a ( by simpa [ funext_iff ] using ha ) ;
    rw [ Submodule.disjoint_def ];
    intro c hc hc'; obtain ⟨ a, rfl ⟩ := h_genCode c hc; specialize hP_zero a; simp_all +decide [ funext_iff, Matrix.vecMul ] ;
    exact fun x => by rw [ show a = 0 from funext fun i => hP_zero ( fun i hi => hc' i hi ) i ] ; simp +decide ;

/-- **Arcs ⇄ MDS codes** (MacWilliams–Sloane, Ch. 11, Thm 8).  For a generator
matrix `G` whose rows are linearly independent (so `dim = k`), the code
`genCode G` is MDS iff `G` is an arc — every `k` columns are linearly
independent. -/
theorem isMDS_genCode_iff_isArc {G : Matrix (Fin k) ι F}
    (hG : LinearIndependent F G) (hk : 0 < k) :
    IsMDS (genCode G) ↔ IsArc G := by
  have hdim : codeDim (genCode G) = k := codeDim_genCode_of_rows_li hG
  have hbot : genCode G ≠ ⊥ := by
    intro h
    have : codeDim (genCode G) = 0 := by rw [h]; simp [codeDim]
    omega
  rw [isMDS_iff_forall_disjoint_vanishing hbot, hdim]
  constructor
  · intro h S hS
    exact (disjoint_vanishingOn_iff_columns_li hG S hS).1 (h S hS)
  · intro h S hS
    exact (disjoint_vanishingOn_iff_columns_li hG S hS).2 (h S hS)

end CodingTheory