import RequestProject.Geometry.PointAtInfinity
import RequestProject.Geometry.Arcs

/-!
# The extended normal rational curve generates an MDS code

This module continues the **geometry** track of
`RequestProject/Geometry/PointAtInfinity.lean`
(`extendedNRCgen_isArc`: the extended normal rational curve over `Option F` is a
`(q+1)`-arc) and `RequestProject/Geometry/Arcs.lean`
(`isMDS_genCode_iff_isArc`: a generator matrix with independent rows generates an
MDS code iff its columns form an arc).

Combining the two, the linear code generated by the extended normal rational
curve is MDS — the classical geometric construction of `[q+1, k, q-k+2]`
Reed–Solomon / MDS codes from the rational normal curve plus its point at
infinity (MacWilliams–Sloane, Ch. 11).

## Main results

* `extendedNRCgen_rows_li` — the rows of the extended NRC generator are linearly
  independent (`1 ≤ k ≤ q+1`).
* `extendedNRC_isMDS` — the code `genCode (extendedNRCgen k)` is MDS.
-/

namespace CodingTheory

open scoped Classical

variable {F : Type*} [Field F] [Fintype F]

/-
The rows of the extended normal rational curve generator matrix are linearly
independent, for `1 ≤ k ≤ q + 1`.
-/
theorem extendedNRCgen_rows_li {k : ℕ} (hk1 : 1 ≤ k) (hk : k ≤ Fintype.card F + 1) :
    LinearIndependent F (extendedNRCgen (F := F) k) := by
  -- Let `S` be a `k`-element subset of `Option F`.
  obtain ⟨S, hS⟩ : ∃ S : Finset (Option F), S.card = k := by
    exact Exists.imp ( by aesop ) ( Finset.exists_subset_card_eq ( show k ≤ Finset.card ( Finset.univ : Finset ( Option F ) ) from by simpa [ Fintype.card_option ] using hk ) );
  -- By `extendedNRCgen_isArc hk1 hk`, the columns of `G` indexed by `S` are linearly independent.
  have h_col_indep : LinearIndependent F (fun i : S => arcColumn (extendedNRCgen (F := F) k) (i : Option F)) := by
    exact extendedNRCgen_isArc hk1 hk S hS;
  have h_row_indep : LinearIndependent F (Matrix.row (Matrix.of (fun r : Fin k => fun i : S => (extendedNRCgen (F := F) k) r i)) : Fin k → S → F) := by
    convert linearIndependent_row_iff_col _ _ |>.2 h_col_indep using 1;
    aesop;
  rw [ Fintype.linearIndependent_iff ] at *;
  intro g hg i;
  exact h_row_indep g ( by ext j; simpa [ Matrix.mulVec, dotProduct, mul_comm ] using congr_fun hg j ) i

/-
**The extended normal rational curve generates an MDS code.**  For
`1 ≤ k ≤ q + 1`, the linear code `genCode (extendedNRCgen k)` over `Option F`
generated by the extended normal rational curve is MDS.
-/
theorem extendedNRC_isMDS {k : ℕ} (hk1 : 1 ≤ k) (hk : k ≤ Fintype.card F + 1) :
    IsMDS (genCode (extendedNRCgen (F := F) k)) := by
  apply (isMDS_genCode_iff_isArc (extendedNRCgen_rows_li hk1 hk) (by omega)).mpr (extendedNRCgen_isArc hk1 hk)

end CodingTheory