/-
# Layer 20: Finitary Fragment & Completeness

This layer defines the finitary fragment of geometric logic (formulas
using only ⊤, ⊥, atoms, ∧, ∨ — no infinitary disjunctions or
existentials) and develops completeness-related results.

## Mathematical Content

1. **Finitary formulas**: The sub-inductive of GeomFormula using only
   ⊤, ⊥, atom, conj, disj.

2. **Completeness framework**: The separation property, its equivalence
   with completeness and enough-points.

3. **Concrete completeness results**: Inconsistent theories are trivially
   complete. Non-derivability witnesses via soundness.

4. **Principal filters**: The principal filter generated by a formula.

## DAG Structure (depends on Layers 10, 12, 14, 17, 19)

```
  separation_iff_complete (★)
       |
  principalFilter ←── SyntacticFilter (Layer 19)
       |
  IsFinitary ←── GeomFormula (Layer 10)
```
-/
import Mathlib
import RequestProject.Foundations.Filters
import RequestProject.Foundations.ToposEquivalence
import RequestProject.Foundations.Applications

namespace Caramello.FinitaryCompleteness

open GeometricLogic SyntacticCategory ClassifyingTopos Filters
     ToposEquivalence

/-! ## Section 1: Finitary Geometric Formulas -/

/-- A geometric formula is finitary if it uses only ⊤, ⊥, atoms, ∧, ∨. -/
inductive IsFinitary {α : Type} : GeomFormula α → Prop where
  | top : IsFinitary .top
  | bot : IsFinitary .bot
  | atom (a : α) : IsFinitary (.atom a)
  | conj {φ ψ} : IsFinitary φ → IsFinitary ψ → IsFinitary (.conj φ ψ)
  | disj {φ ψ} : IsFinitary φ → IsFinitary ψ → IsFinitary (.disj φ ψ)

/-- A geometric sequent is finitary if both components are. -/
def IsFinitarySequent {α : Type} (s : GeomSequent α) : Prop :=
  IsFinitary s.antecedent ∧ IsFinitary s.consequent

/-- A theory is finitary if all its axioms are finitary. -/
def IsFinitaryTheory {α : Type} (T : GeomTheory α) : Prop :=
  ∀ s ∈ T, IsFinitarySequent s

/-- Finitary formulas are closed under conjunction. -/
theorem isFinitary_conj {α : Type} {φ ψ : GeomFormula α}
    (hφ : IsFinitary φ) (hψ : IsFinitary ψ) :
    IsFinitary (.conj φ ψ) :=
  IsFinitary.conj hφ hψ

/-- Finitary formulas are closed under disjunction. -/
theorem isFinitary_disj {α : Type} {φ ψ : GeomFormula α}
    (hφ : IsFinitary φ) (hψ : IsFinitary ψ) :
    IsFinitary (.disj φ ψ) :=
  IsFinitary.disj hφ hψ

/-! ## Section 2: Principal Filters -/

/-- The principal filter generated by φ: all formulas derivable from φ. -/
def principalFilter {α : Type} (T : GeomTheory α)
    (φ : GeomFormula α) : SyntacticFilter T where
  carrier := { ψ | T ⊢g φ ⟹ ψ }
  top_mem := Derivable.top_intro φ
  upward := fun hψ hle => Derivable.trans hψ hle
  conj_mem := fun hψ₁ hψ₂ => Derivable.conj_intro hψ₁ hψ₂

/-- φ is in its own principal filter. -/
theorem mem_principalFilter {α : Type} {T : GeomTheory α}
    (φ : GeomFormula α) : φ ∈ (principalFilter T φ).carrier :=
  Derivable.refl φ

/-- The principal filter of φ is proper iff T ⊬ φ ⟹ ⊥. -/
theorem principalFilter_proper_iff {α : Type} {T : GeomTheory α}
    (φ : GeomFormula α) :
    (principalFilter T φ).isProper ↔ ¬ (T ⊢g φ ⟹ .bot) :=
  Iff.rfl

/-! ## Section 3: Completeness Framework -/

/-- A filter F separates φ from ψ if φ ∈ F but ψ ∉ F. -/
def FilterSeparates {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (φ ψ : GeomFormula α) : Prop :=
  φ ∈ F.carrier ∧ ψ ∉ F.carrier

/-- If a filter separates φ from ψ, then T ⊬ φ ⟹ ψ. -/
theorem filter_separates_non_derivable {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (φ ψ : GeomFormula α)
    (h : FilterSeparates F φ ψ) : ¬ (T ⊢g φ ⟹ ψ) :=
  fun hd => h.2 (F.upward h.1 hd)

/-- A theory has the separation property if non-derivable sequents
    have separating models. -/
def HasSeparation {α : Type} (T : GeomTheory α) : Prop :=
  ∀ φ ψ : GeomFormula α,
    ¬ (T ⊢g φ ⟹ ψ) →
    ∃ v : α → Prop, T.Model v ∧ φ.eval v ∧ ¬ ψ.eval v

/-- ★ The separation property is equivalent to completeness. -/
theorem separation_iff_complete {α : Type} {T : GeomTheory α} :
    HasSeparation T ↔ ToposEquivalence.IsComplete T := by
  constructor
  · intro hsep φ ψ hvalid
    by_contra hnd
    obtain ⟨v, hm, hφ, hψ⟩ := hsep φ ψ hnd
    exact hψ (hvalid v hm hφ)
  · intro hcomp φ ψ hnd
    by_contra hall
    push_neg at hall
    exact hnd (hcomp φ ψ hall)

/-- Separation implies HasEnoughPoints. -/
theorem separation_implies_enough_points {α : Type} {T : GeomTheory α}
    (h : HasSeparation T) : HasEnoughPoints T := by
  have hc := separation_iff_complete.mp h
  exact complete_implies_enough_points hc

/-! ## Section 4: Concrete Completeness Results -/

/-- Inconsistent theories are trivially complete. -/
theorem inconsistent_theory_complete {α : Type} {T : GeomTheory α}
    (hinc : T ⊢g .top ⟹ .bot) :
    ToposEquivalence.IsComplete T :=
  fun φ ψ _ =>
    Derivable.trans (Derivable.trans (Derivable.top_intro φ) hinc) (Derivable.bot_elim ψ)

/-- Completeness for a theory with a unique model: validity at the
    unique model suffices. -/
theorem unique_model_valid {α : Type} {T : GeomTheory α}
    (v₀ : α → Prop) (_hv₀ : T.Model v₀)
    (huniq : ∀ v : α → Prop, T.Model v → v = v₀)
    {φ ψ : GeomFormula α}
    (heval : φ.eval v₀ → ψ.eval v₀) :
    ∀ v : α → Prop, T.Model v → φ.eval v → ψ.eval v := by
  intro v hm hφ
  rw [huniq v hm] at hφ ⊢
  exact heval hφ

/-! ## Section 5: Non-Derivability Witnesses -/

/-- If we can find a model separating φ from ψ, then T ⊬ φ ⟹ ψ. -/
theorem non_derivable_of_separating_model {α : Type} {T : GeomTheory α}
    {φ ψ : GeomFormula α}
    (v : α → Prop) (hm : T.Model v) (hφ : φ.eval v) (hψ : ¬ψ.eval v) :
    ¬ (T ⊢g φ ⟹ ψ) :=
  non_derivable_witness v hm hφ hψ

/-- The empty theory does not derive atom a ⊢ ⊥. -/
theorem empty_theory_atom_consistent {α : Type} (a : α) :
    ¬ ((∅ : GeomTheory α) ⊢g .atom a ⟹ .bot) :=
  non_derivable_witness (fun _ => True) (fun _ h => absurd h id) trivial id

/-- The empty theory does not derive ⊤ ⊢ ⊥. -/
theorem empty_theory_consistent_deriv :
    ¬ ((∅ : GeomTheory Empty) ⊢g .top ⟹ .bot) :=
  non_derivable_witness (fun e => e.elim) (fun _ h => absurd h id) trivial id

/-! ## Section 6: Consistency Lemmas for Completeness Arguments -/

/-- If φ ∧ ψ is consistent (doesn't derive ⊥), then φ is consistent. -/
theorem conj_consistent_left {α : Type} {T : GeomTheory α}
    {φ ψ : GeomFormula α} (h : ¬ T ⊢g .conj φ ψ ⟹ .bot) :
    ¬ T ⊢g φ ⟹ .bot :=
  fun habs => h (Derivable.trans (Derivable.conj_elim_left _ _) habs)

/-- If φ ∧ ψ is consistent (doesn't derive ⊥), then ψ is consistent. -/
theorem conj_consistent_right {α : Type} {T : GeomTheory α}
    {φ ψ : GeomFormula α} (h : ¬ T ⊢g .conj φ ψ ⟹ .bot) :
    ¬ T ⊢g ψ ⟹ .bot :=
  fun habs => h (Derivable.trans (Derivable.conj_elim_right _ _) habs)

/-- If φ ∨ ψ derives ⊥, then both φ and ψ derive ⊥. -/
theorem disj_inconsistent {α : Type} {T : GeomTheory α}
    {φ ψ : GeomFormula α} (h : T ⊢g .disj φ ψ ⟹ .bot) :
    (T ⊢g φ ⟹ .bot) ∧ (T ⊢g ψ ⟹ .bot) := by
  constructor
  · exact Derivable.trans (Derivable.disj_intro_left _ _) h
  · exact Derivable.trans (Derivable.disj_intro_right _ _) h

/-- If φ is consistent with T, then the principal filter of φ is proper. -/
theorem consistent_principal_proper {α : Type} {T : GeomTheory α}
    {φ : GeomFormula α} (h : ¬ T ⊢g φ ⟹ .bot) :
    (principalFilter T φ).isProper :=
  h

/-! ## Section 7: Theory Classification -/

/-- The empty theory is finitary. -/
theorem empty_isFinitary {α : Type} : IsFinitaryTheory (∅ : GeomTheory α) :=
  fun _ h => absurd h id

/-- Singleton theories with finitary sequents are finitary. -/
theorem singleton_isFinitary {α : Type} {s : GeomSequent α}
    (h : IsFinitarySequent s) :
    IsFinitaryTheory ({s} : GeomTheory α) := by
  intro s' hs'
  rw [Set.mem_singleton_iff] at hs'
  subst hs'; exact h

/-- The union of two finitary theories is finitary. -/
theorem union_isFinitary {α : Type} {T₁ T₂ : GeomTheory α}
    (h₁ : IsFinitaryTheory T₁) (h₂ : IsFinitaryTheory T₂) :
    IsFinitaryTheory (T₁ ∪ T₂) := by
  intro s hs
  rcases hs with h | h
  · exact h₁ s h
  · exact h₂ s h

/-! ## Section 8: Derivability and Model Existence -/

/-- If T is consistent (⊤ ⊬ ⊥) and has the separation property,
    then T has a model. -/
theorem consistent_has_model_of_separation {α : Type} {T : GeomTheory α}
    (hsep : HasSeparation T) (hcons : ¬ T ⊢g .top ⟹ .bot) :
    ∃ v : α → Prop, T.Model v := by
  obtain ⟨v, hm, _, _⟩ := hsep .top .bot hcons
  exact ⟨v, hm⟩

/-- Contrapositive: if T has no models, then T ⊢ ⊤ ⟹ ⊥. -/
theorem no_models_derives_bot {α : Type} {T : GeomTheory α}
    (hcomp : ToposEquivalence.IsComplete T) (hno : ¬ ∃ v : α → Prop, T.Model v) :
    T ⊢g .top ⟹ .bot := by
  apply hcomp
  intro v hm
  exact absurd ⟨v, hm⟩ hno

/-! ## Section 9: Finitary Closure Properties -/

/-- mapAtoms preserves finitaryness. -/
theorem isFinitary_mapAtoms {α β : Type} {φ : GeomFormula α}
    (hφ : IsFinitary φ) (f : α → β) : IsFinitary (φ.mapAtoms f) := by
  induction hφ with
  | top => exact IsFinitary.top
  | bot => exact IsFinitary.bot
  | atom a => exact IsFinitary.atom (f a)
  | conj _ _ ih₁ ih₂ => exact IsFinitary.conj ih₁ ih₂
  | disj _ _ ih₁ ih₂ => exact IsFinitary.disj ih₁ ih₂

/-- The image of a finitary theory under atom renaming is finitary. -/
theorem isFinitaryTheory_rename {α β : Type} {T : GeomTheory α}
    (hfin : IsFinitaryTheory T) (e : α ≃ β) :
    IsFinitaryTheory (Caramello.Applications.theoryRename e T) := by
  intro s hs
  simp [Caramello.Applications.theoryRename] at hs
  obtain ⟨s', hs', rfl⟩ := hs
  obtain ⟨h₁, h₂⟩ := hfin s' hs'
  exact ⟨isFinitary_mapAtoms h₁ e, isFinitary_mapAtoms h₂ e⟩

/-! ## Section 10: Summary

This layer establishes:

1. **Finitary formulas**: A well-defined sub-class of geometric formulas.

2. **Completeness framework**: The separation property ↔ completeness ↔
   enough points.

3. **Non-derivability tools**: Soundness-based witnesses.

4. **Consistency lemmas**: Structural properties supporting completeness
   arguments via Zorn's lemma.

5. **Finitary closure**: Finitaryness is preserved by atom renaming.

Key theorems:
- `separation_iff_complete`: separation ↔ completeness
- `inconsistent_theory_complete`: inconsistent theories are complete
- `separation_implies_enough_points`: separation → enough points
- `non_derivable_of_separating_model`: models witness non-derivability
- `isFinitary_mapAtoms`: finitaryness preserved by atom maps
-/

end Caramello.FinitaryCompleteness
