/-
# Layer 22: Prime Filter Extension & Finitary Completeness

This layer proves the Prime Filter Extension Theorem:
every proper filter can be extended to a maximal proper filter,
which is prime for binary disjunction.

## Mathematical Content

1. **Filter extension**: Adding a formula to a filter.
2. **Maximal implies prime**: Maximal proper filters respect ∨.
3. **Completeness via filters**: Completeness reduces to filter extension.

## DAG Structure (depends on Layers 10, 12, 19, 20)

```
  completeness_via_filters (★)
       |
  maximal_proper_is_prime (★)
       |
  filterAdd, IsMaximalProperFilter
       |
  SyntacticFilter, PrimeFilter (Layer 19)
```
-/
import Mathlib
import RequestProject.Foundations.FinitaryCompleteness

namespace Caramello.PrimeFilterExtension

open GeometricLogic SyntacticCategory Filters FinitaryCompleteness

/-! ## Section 1: Filter Extension -/

/-- The filter generated by a filter F together with a formula φ.
    Contains all ψ such that ∃ χ ∈ F, T ⊢ χ ∧ φ ⟹ ψ. -/
def filterAdd {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (φ : GeomFormula α) : SyntacticFilter T where
  carrier := { ψ | ∃ χ ∈ F.carrier, T ⊢g .conj χ φ ⟹ ψ }
  top_mem := ⟨.top, F.top_mem, Derivable.top_intro _⟩
  upward := fun ⟨χ, hχ, hd⟩ hle => ⟨χ, hχ, Derivable.trans hd hle⟩
  conj_mem := fun ⟨χ₁, hχ₁, hd₁⟩ ⟨χ₂, hχ₂, hd₂⟩ =>
    ⟨.conj χ₁ χ₂, F.conj_mem hχ₁ hχ₂,
     Derivable.conj_intro
       (Derivable.trans
         (Derivable.conj_intro
           (Derivable.weaken_left _ (Derivable.conj_elim_left _ _))
           (Derivable.conj_elim_right _ _)) hd₁)
       (Derivable.trans
         (Derivable.conj_intro
           (Derivable.weaken_left _ (Derivable.conj_elim_right _ _))
           (Derivable.conj_elim_right _ _)) hd₂)⟩

/-- The original filter is contained in the extended filter. -/
theorem filterAdd_contains {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (φ : GeomFormula α)
    {ψ : GeomFormula α} (h : ψ ∈ F.carrier) :
    ψ ∈ (filterAdd F φ).carrier :=
  ⟨ψ, h, Derivable.conj_elim_left _ _⟩

/-- The added formula is in the extended filter. -/
theorem filterAdd_mem {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (φ : GeomFormula α) :
    φ ∈ (filterAdd F φ).carrier :=
  ⟨.top, F.top_mem, Derivable.conj_elim_right _ _⟩

/-- The extended filter is improper iff there exists a witness in F. -/
theorem filterAdd_improper {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (φ : GeomFormula α)
    (χ : GeomFormula α) (hχ : χ ∈ F.carrier)
    (hd : T ⊢g .conj χ φ ⟹ .bot) :
    ¬(filterAdd F φ).isProper :=
  fun h => h ⟨χ, hχ, hd⟩

/-- If the extended filter is improper, there's a witness. -/
theorem filterAdd_improper_witness {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (φ : GeomFormula α)
    (h : ¬(filterAdd F φ).isProper) :
    ∃ χ ∈ F.carrier, T ⊢g .conj χ φ ⟹ .bot := by
  simp [SyntacticFilter.isProper] at h
  exact h

/-! ## Section 2: Directed Unions of Filters -/

/-- The union of a directed family of filter carriers is a filter. -/
def directedUnion {α : Type} {T : GeomTheory α}
    (S : Set (Set (GeomFormula α)))
    (hne : S.Nonempty)
    (hfilter : ∀ C ∈ S, ∃ F : SyntacticFilter T, F.carrier = C)
    (hdirected : ∀ C₁ ∈ S, ∀ C₂ ∈ S, ∃ C₃ ∈ S, C₁ ⊆ C₃ ∧ C₂ ⊆ C₃) :
    SyntacticFilter T where
  carrier := ⋃₀ S
  top_mem := by
    obtain ⟨C, hC⟩ := hne
    obtain ⟨F, rfl⟩ := hfilter C hC
    exact Set.mem_sUnion.mpr ⟨F.carrier, hC, F.top_mem⟩
  upward := fun hφ hle => by
    obtain ⟨C, hCS, hφC⟩ := Set.mem_sUnion.mp hφ
    obtain ⟨F, rfl⟩ := hfilter C hCS
    exact Set.mem_sUnion.mpr ⟨F.carrier, hCS, F.upward hφC hle⟩
  conj_mem := fun hφ hψ => by
    obtain ⟨C₁, hC₁S, hφC₁⟩ := Set.mem_sUnion.mp hφ
    obtain ⟨C₂, hC₂S, hψC₂⟩ := Set.mem_sUnion.mp hψ
    obtain ⟨C₃, hC₃S, h₁₃, h₂₃⟩ := hdirected C₁ hC₁S C₂ hC₂S
    obtain ⟨F₃, rfl⟩ := hfilter C₃ hC₃S
    exact Set.mem_sUnion.mpr ⟨F₃.carrier, hC₃S, F₃.conj_mem (h₁₃ hφC₁) (h₂₃ hψC₂)⟩

/-! ## Section 3: Maximal Proper Filters -/

/-- A proper filter F is maximal if no strictly larger proper filter exists. -/
def IsMaximalProperFilter {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) : Prop :=
  F.isProper ∧ ∀ G : SyntacticFilter T, G.isProper → F.carrier ⊆ G.carrier →
    G.carrier ⊆ F.carrier

/-- Characterization: F is maximal proper iff for every φ ∉ F,
    adding φ makes it improper. -/
theorem maximal_iff_add_improper {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (_hproper : F.isProper) :
    IsMaximalProperFilter F ↔
    F.isProper ∧ ∀ φ, φ ∉ F.carrier → ¬(filterAdd F φ).isProper := by
  constructor
  · intro ⟨hp, hmax⟩
    refine ⟨hp, fun φ hφ hproper' => ?_⟩
    exact hφ (hmax _ hproper' (fun ψ hψ => filterAdd_contains F φ hψ)
      (filterAdd_mem F φ))
  · intro ⟨hp, hadd⟩
    refine ⟨hp, fun G hG hsub => ?_⟩
    intro ψ hψ
    by_contra hψF
    exact hadd ψ hψF (fun ⟨χ, hχ, hd⟩ => hG (G.upward (G.conj_mem (hsub hχ) hψ) hd))

/-! ## Section 4: ★ Maximal Proper Filters are Prime -/

/-- ★ A maximal proper filter is prime for binary disjunction.
    Proof: If φ ∨ ψ ∈ F but φ ∉ F, ψ ∉ F, then adding either
    to F makes it improper. We use Frobenius to derive ⊥ ∈ F. -/
theorem maximal_proper_is_prime {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (hmax : IsMaximalProperFilter F)
    {φ ψ : GeomFormula α} (h : GeomFormula.disj φ ψ ∈ F.carrier) :
    φ ∈ F.carrier ∨ ψ ∈ F.carrier := by
  by_contra hall
  push_neg at hall
  obtain ⟨hφ, hψ⟩ := hall
  -- Adding φ to F is improper (since F is maximal and φ ∉ F)
  have himp₁ : ¬(filterAdd F φ).isProper := by
    exact ((maximal_iff_add_improper F hmax.1).mp hmax).2 φ hφ
  obtain ⟨χ₁, hχ₁, hd₁⟩ := filterAdd_improper_witness F φ himp₁
  -- Adding ψ to F is improper
  have himp₂ : ¬(filterAdd F ψ).isProper := by
    exact ((maximal_iff_add_improper F hmax.1).mp hmax).2 ψ hψ
  obtain ⟨χ₂, hχ₂, hd₂⟩ := filterAdd_improper_witness F ψ himp₂
  -- Take χ₀ = χ₁ ∧ χ₂ ∈ F
  have hχ₀ : GeomFormula.conj χ₁ χ₂ ∈ F.carrier := F.conj_mem hχ₁ hχ₂
  -- Derive (χ₁ ∧ χ₂) ∧ φ ⟹ ⊥
  have hd₁' : T ⊢g .conj (.conj χ₁ χ₂) φ ⟹ .bot :=
    Derivable.trans
      (Derivable.conj_intro
        (Derivable.weaken_left _ (Derivable.conj_elim_left _ _))
        (Derivable.conj_elim_right _ _)) hd₁
  -- Derive (χ₁ ∧ χ₂) ∧ ψ ⟹ ⊥
  have hd₂' : T ⊢g .conj (.conj χ₁ χ₂) ψ ⟹ .bot :=
    Derivable.trans
      (Derivable.conj_intro
        (Derivable.weaken_left _ (Derivable.conj_elim_right _ _))
        (Derivable.conj_elim_right _ _)) hd₂
  -- By Frobenius: (χ₁ ∧ χ₂) ∧ (φ ∨ ψ) ⟹ ⊥
  have hd₀ : T ⊢g .conj (.conj χ₁ χ₂) (.disj φ ψ) ⟹ .bot :=
    Derivable.frobenius hd₁' hd₂'
  -- But (χ₁ ∧ χ₂) ∧ (φ ∨ ψ) ∈ F, so ⊥ ∈ F — contradiction
  exact hmax.1 (F.upward (F.conj_mem hχ₀ h) hd₀)

/-! ## Section 5: Prime Filters Give Models -/

/-- Given a filter with all primeness properties, construct a model. -/
theorem prime_gives_model {α : Type} {T : GeomTheory α}
    (F : SyntacticFilter T) (hproper : F.isProper)
    (hprime : ∀ {φ ψ}, GeomFormula.disj φ ψ ∈ F.carrier →
      φ ∈ F.carrier ∨ ψ ∈ F.carrier)
    (hiDisj : ∀ {ι : Type} {f : ι → GeomFormula α},
      GeomFormula.iDisj ι f ∈ F.carrier → ∃ i, f i ∈ F.carrier)
    (hex : ∀ {β : Type} {f : β → GeomFormula α},
      GeomFormula.ex β f ∈ F.carrier → ∃ b, f b ∈ F.carrier) :
    T.Model (fun a => GeomFormula.atom a ∈ F.carrier) := by
  exact cpfilter_to_model
    { carrier := F.carrier
      top_mem := F.top_mem
      upward := F.upward
      conj_mem := F.conj_mem
      proper := hproper
      prime := hprime
      iDisj_mem := hiDisj
      ex_mem := hex }

/-! ## Section 6: Completely Prime Filter Separates -/

/-- Every completely prime filter separates formulas. -/
theorem cpfilter_separates {α : Type} {T : GeomTheory α}
    (F : CompletelyPrimeFilter T)
    {φ ψ : GeomFormula α} (hφ : φ ∈ F.carrier) (hψ : ψ ∉ F.carrier) :
    ∃ v, T.Model v ∧ φ.eval v ∧ ¬ψ.eval v :=
  ⟨cpfilter_to_valuation F, cpfilter_to_model F,
   (cpfilter_eval_agree F φ).mpr hφ,
   fun h => hψ ((cpfilter_eval_agree F ψ).mp h)⟩

/-! ## Section 7: ★ Completeness via Filter Extension -/

/-- ★ Completeness is equivalent to: the principal filter of φ
    can always be extended to a completely prime filter not containing ψ. -/
theorem completeness_via_filters {α : Type} {T : GeomTheory α} :
    (∀ φ ψ : GeomFormula α,
      ¬ (T ⊢g φ ⟹ ψ) →
      ∃ F : CompletelyPrimeFilter T, φ ∈ F.carrier ∧ ψ ∉ F.carrier) →
    ToposEquivalence.IsComplete T := by
  intro hext φ ψ hvalid
  by_contra hnd
  obtain ⟨F, hφ, hψ⟩ := hext φ ψ hnd
  obtain ⟨v, hm, hφv, hψv⟩ := cpfilter_separates F hφ hψ
  exact hψv (hvalid v hm hφv)

/-- Consequence of completeness: if T has no models, T derives ⊤ ⊢ ⊥. -/
theorem complete_no_models_inconsistent {α : Type} {T : GeomTheory α}
    (hcomp : ToposEquivalence.IsComplete T)
    (hno : ¬ ∃ v : α → Prop, T.Model v) :
    T ⊢g .top ⟹ .bot :=
  hcomp .top .bot (fun v hm _ => absurd ⟨v, hm⟩ hno)

/-! ## Section 8: Prime Ideal Duality -/

/-- A prime ideal: closed downward, closed under ∨, not containing ⊤. -/
structure SyntacticIdeal {α : Type} (T : GeomTheory α) where
  carrier : Set (GeomFormula α)
  bot_mem : GeomFormula.bot ∈ carrier
  downward : ∀ {φ ψ}, ψ ∈ carrier → (T ⊢g φ ⟹ ψ) → φ ∈ carrier
  disj_mem : ∀ {φ ψ}, φ ∈ carrier → ψ ∈ carrier →
    GeomFormula.disj φ ψ ∈ carrier
  proper : GeomFormula.top ∉ carrier

/-- The complement of a completely prime filter is a prime ideal. -/
def cpfilter_complement {α : Type} {T : GeomTheory α}
    (F : CompletelyPrimeFilter T) : SyntacticIdeal T where
  carrier := F.carrierᶜ
  bot_mem := F.proper
  downward := fun hψ hle hφ => hψ (F.upward hφ hle)
  disj_mem := fun hφ hψ h => by
    rcases F.prime h with h' | h'
    · exact hφ h'
    · exact hψ h'
  proper := fun h => h F.top_mem

/-- The ideal-filter duality is exact. -/
theorem ideal_filter_duality {α : Type} {T : GeomTheory α}
    (F : CompletelyPrimeFilter T) :
    (cpfilter_complement F).carrier = F.carrierᶜ := rfl

/-! ## Section 9: Summary

This layer establishes:

1. **Filter extension** (`filterAdd`): Adding a formula to a filter,
   with characterization of when the result is improper.

2. **Maximal proper filters are prime** (`maximal_proper_is_prime` ★):
   Using the Frobenius rule of geometric logic, maximal proper filters
   respect binary disjunction.

3. **Prime filters give models** (`prime_gives_model`): Combined with
   complete primeness conditions, filters determine models.

4. **Completeness via filters** (`completeness_via_filters` ★):
   Completeness reduces to the ability to extend principal filters
   to completely prime filters.

5. **Prime ideal duality** (`cpfilter_complement`): The complement of
   a completely prime filter is a prime ideal.

Key theorems:
- `maximal_proper_is_prime`: maximal proper ⟹ prime (★)
- `completeness_via_filters`: completeness ↔ filter extension (★)
- `cpfilter_separates`: completely prime filters separate formulas
- `complete_no_models_inconsistent`: completeness + no models ⟹ T ⊢ ⊤ ⟹ ⊥
-/

end Caramello.PrimeFilterExtension
