/-
# Layer 23: Topological Spectrum of a Theory

The spectrum of a geometric theory (the set of completely prime
filters / models) carries a natural topology — the spectral topology.
This connects the model-theoretic world to point-set topology.

## Mathematical Content

1. **Spectral topology**: The topology generated by basic opens D(φ).
2. **Continuity of spectral maps**: Theory morphisms induce continuous maps.
3. **Compactness properties**: Basic opens and their intersections.
4. **Separation axioms**: T₀ separation from the derivability relation.

## DAG Structure (depends on Layers 10, 12, 19, 21)

```
  spectral_T0 (★)
       |
  spectralMap_continuous ←── spectral_topology
       |
  basicOpen frame properties (Layer 21)
       |
  Spectrum, CompletelyPrimeFilter (Layer 19)
```
-/
import Mathlib
import RequestProject.Foundations.LatticeTheories
import RequestProject.Foundations.PrimeFilterExtension

namespace Caramello.TopologicalSpectrum

open GeometricLogic SyntacticCategory Filters
     LatticeTheories PrimeFilterExtension

/-! ## Section 1: The Spectral Topology

The spectral topology on Spec(T) has basic opens D(φ) = {p | φ ∈ p}.
We define it as the topology generated by these basic opens.
-/

/-- The spectral topology on the spectrum of T: generated by basic opens D(φ). -/
def spectralTopology {α : Type} (T : GeomTheory α) :
    TopologicalSpace (Spectrum T) :=
  TopologicalSpace.generateFrom { U | ∃ φ : GeomFormula α, U = basicOpen φ }

/-- Basic opens are open in the spectral topology. -/
theorem basicOpen_isOpen {α : Type} {T : GeomTheory α}
    (φ : GeomFormula α) :
    @IsOpen _ (spectralTopology T) (basicOpen φ) :=
  TopologicalSpace.GenerateOpen.basic _ ⟨φ, rfl⟩

/-- The whole space is open (rewritten via D(⊤)). -/
theorem univ_isOpen {α : Type} {T : GeomTheory α} :
    @IsOpen _ (spectralTopology T) Set.univ := by
  rw [← basicOpen_top]
  exact basicOpen_isOpen _

/-- The empty set is open (rewritten via D(⊥)). -/
theorem empty_isOpen {α : Type} {T : GeomTheory α} :
    @IsOpen _ (spectralTopology T) ∅ := by
  rw [← basicOpen_bot]
  exact basicOpen_isOpen _

/-! ## Section 2: Frame Properties of Basic Opens

The basic opens form a frame: they are closed under finite
intersections and arbitrary unions (for geometric formulas).
-/

/-- D(φ ∧ ψ) = D(φ) ∩ D(ψ): basic opens are closed under ∩. -/
theorem basicOpen_inter {α : Type} {T : GeomTheory α}
    (φ ψ : GeomFormula α) :
    basicOpen (T := T) (.conj φ ψ) = basicOpen φ ∩ basicOpen ψ :=
  basicOpen_conj φ ψ

/-- D(φ ∨ ψ) = D(φ) ∪ D(ψ): basic opens are closed under ∪. -/
theorem basicOpen_union {α : Type} {T : GeomTheory α}
    (φ ψ : GeomFormula α) :
    basicOpen (T := T) (.disj φ ψ) = basicOpen φ ∪ basicOpen ψ :=
  basicOpen_disj φ ψ

/-- D(⋁ᵢ φᵢ) = ⋃ᵢ D(φᵢ): basic opens respect infinitary unions. -/
theorem basicOpen_iUnion {α : Type} {T : GeomTheory α}
    (ι : Type) (f : ι → GeomFormula α) :
    basicOpen (T := T) (.iDisj ι f) = ⋃ i, basicOpen (f i) :=
  basicOpen_iDisj ι f

/-! ## Section 3: Derivability and Topology

The derivability relation T ⊢ φ ⟹ ψ is reflected in the
inclusion of basic opens: D(φ) ⊆ D(ψ).
-/

/-- Derivability implies containment of basic opens. -/
theorem derivable_implies_basicOpen_sub {α : Type} {T : GeomTheory α}
    {φ ψ : GeomFormula α} (h : T ⊢g φ ⟹ ψ) :
    basicOpen (T := T) φ ⊆ basicOpen ψ :=
  basicOpen_mono h

/-- T-equivalent formulas have the same basic open. -/
theorem tequiv_basicOpen_eq {α : Type} {T : GeomTheory α}
    {φ ψ : GeomFormula α} (h : T ⊢g φ ⟺ ψ) :
    basicOpen (T := T) φ = basicOpen ψ :=
  basicOpen_tequiv h

/-- D(⊤) is the whole spectrum. -/
theorem basicOpen_top_eq_univ {α : Type} {T : GeomTheory α} :
    basicOpen (T := T) .top = Set.univ :=
  basicOpen_top

/-- D(⊥) is empty. -/
theorem basicOpen_bot_eq_empty {α : Type} {T : GeomTheory α} :
    basicOpen (T := T) .bot = ∅ :=
  basicOpen_bot

/-! ## Section 4: T₀ Separation

The spectral topology is T₀: distinct points are topologically
distinguishable. Two points p₁ ≠ p₂ have different carriers,
so there exists a formula φ with φ ∈ p₁ but φ ∉ p₂ (or vice versa),
giving a basic open separating them.
-/

/-
Two distinct points are separated by a basic open.
-/
theorem distinct_points_separated {α : Type} {T : GeomTheory α}
    (p₁ p₂ : Spectrum T) (hne : p₁.carrier ≠ p₂.carrier) :
    ∃ φ, (φ ∈ p₁.carrier ∧ φ ∉ p₂.carrier) ∨
         (φ ∉ p₁.carrier ∧ φ ∈ p₂.carrier) := by
  grind

/-- The spectral topology is T₀ (Kolmogorov). -/
theorem spectral_T0 {α : Type} {T : GeomTheory α}
    (p₁ p₂ : Spectrum T)
    (h : ∀ U : Set (Spectrum T), @IsOpen _ (spectralTopology T) U →
      (p₁ ∈ U ↔ p₂ ∈ U)) :
    p₁.carrier = p₂.carrier := by
  ext φ
  have := h (basicOpen φ) (basicOpen_isOpen φ)
  exact this

/-! ## Section 5: Spectral Map Continuity -/

/-
Spectral maps are continuous with respect to the spectral topology.
-/
theorem spectralMap_continuous {α β : Type}
    {T₁ : GeomTheory α} {T₂ : GeomTheory β}
    (σ : TheoryMorphism T₁ T₂) :
    @Continuous _ _ (spectralTopology T₂) (spectralTopology T₁)
      (spectralMap σ) := by
  apply_rules [ continuous_generateFrom_iff.mpr ];
  simp +zetaDelta at *;
  exact fun φ => by rw [ spectralMap_preimage_basicOpen ] ; exact basicOpen_isOpen _;;

/-! ## Section 6: The Specialization Order

The specialization order on the spectrum: p₁ ≤ p₂ iff
every open set containing p₂ also contains p₁.
For the spectral topology, this is: p₁.carrier ⊆ p₂.carrier.
-/

/-- The specialization order on the spectrum. -/
def specializationOrder {α : Type} {T : GeomTheory α} :
    Preorder (Spectrum T) where
  le := fun p₁ p₂ => p₁.carrier ⊆ p₂.carrier
  le_refl := fun _ => Set.Subset.rfl
  le_trans := fun _ _ _ h₁ h₂ => Set.Subset.trans h₁ h₂

/-- Specialization order agrees with basic open containment. -/
theorem specialization_iff_basicOpen {α : Type} {T : GeomTheory α}
    (p₁ p₂ : Spectrum T) :
    p₁.carrier ⊆ p₂.carrier ↔
    ∀ φ, p₁ ∈ basicOpen φ → p₂ ∈ basicOpen φ :=
  Iff.rfl

/-! ## Section 7: Irreducible Closed Sets

A closed set in the spectral topology is irreducible if it
cannot be written as a union of two proper closed subsets.
The generic points of irreducible closed sets correspond to
prime filters (as opposed to completely prime filters).
-/

/-- The vanishing set V(φ) = {p | φ ∉ p} = complement of D(φ). -/
def vanishingSet {α : Type} {T : GeomTheory α}
    (φ : GeomFormula α) : Set (Spectrum T) :=
  { p | φ ∉ p.carrier }

/-- V(φ) is the complement of D(φ). -/
theorem vanishingSet_eq_compl {α : Type} {T : GeomTheory α}
    (φ : GeomFormula α) :
    vanishingSet (T := T) φ = (basicOpen φ)ᶜ := rfl

/-- V(⊤) is empty: ⊤ is in every filter. -/
theorem vanishingSet_top {α : Type} {T : GeomTheory α} :
    vanishingSet (T := T) .top = ∅ := by
  ext p; simp [vanishingSet]; exact p.top_mem

/-- V(⊥) is the whole spectrum: ⊥ is in no filter. -/
theorem vanishingSet_bot {α : Type} {T : GeomTheory α} :
    vanishingSet (T := T) .bot = Set.univ := by
  ext p; simp [vanishingSet]; exact p.proper

/-- V(φ ∧ ψ) ⊇ V(φ) ∪ V(ψ). -/
theorem vanishingSet_conj_superset {α : Type} {T : GeomTheory α}
    (φ ψ : GeomFormula α) :
    vanishingSet (T := T) φ ∪ vanishingSet ψ ⊆ vanishingSet (.conj φ ψ) := by
  intro p hp
  simp [vanishingSet] at hp ⊢
  intro h
  rcases hp with hφ | hψ
  · exact hφ (p.upward h (Derivable.conj_elim_left _ _))
  · exact hψ (p.upward h (Derivable.conj_elim_right _ _))

/-- V(φ ∨ ψ) = V(φ) ∩ V(ψ). -/
theorem vanishingSet_disj {α : Type} {T : GeomTheory α}
    (φ ψ : GeomFormula α) :
    vanishingSet (T := T) (.disj φ ψ) = vanishingSet φ ∩ vanishingSet ψ := by
  ext p
  simp [vanishingSet]
  constructor
  · intro h
    constructor
    · intro hφ; exact h (p.upward hφ (Derivable.disj_intro_left _ _))
    · intro hψ; exact h (p.upward hψ (Derivable.disj_intro_right _ _))
  · intro ⟨hφ, hψ⟩ h
    rcases p.prime h with h' | h'
    · exact hφ h'
    · exact hψ h'

/-! ## Section 8: The Evaluation Map

The evaluation map sends a point p and a formula φ to the
truth value φ ∈ p. This is the "universal evaluation"
that all concrete evaluations factor through.
-/

/-- The universal evaluation: given p ∈ Spec(T) and φ, decide φ ∈ p. -/
def universalEval {α : Type} {T : GeomTheory α}
    (p : Spectrum T) (φ : GeomFormula α) : Prop :=
  φ ∈ p.carrier

/-- Universal evaluation is monotone in φ. -/
theorem universalEval_monotone {α : Type} {T : GeomTheory α}
    (p : Spectrum T) {φ ψ : GeomFormula α} (h : T ⊢g φ ⟹ ψ)
    (hφ : universalEval p φ) : universalEval p ψ :=
  p.upward hφ h

/-- Universal evaluation preserves ⊤. -/
theorem universalEval_top {α : Type} {T : GeomTheory α}
    (p : Spectrum T) : universalEval p .top :=
  p.top_mem

/-- Universal evaluation rejects ⊥. -/
theorem universalEval_bot {α : Type} {T : GeomTheory α}
    (p : Spectrum T) : ¬ universalEval p .bot :=
  p.proper

/-- Universal evaluation preserves ∧. -/
theorem universalEval_conj {α : Type} {T : GeomTheory α}
    (p : Spectrum T) (φ ψ : GeomFormula α) :
    universalEval p (.conj φ ψ) ↔ universalEval p φ ∧ universalEval p ψ := by
  constructor
  · intro h
    exact ⟨p.upward h (Derivable.conj_elim_left _ _),
           p.upward h (Derivable.conj_elim_right _ _)⟩
  · intro ⟨hφ, hψ⟩; exact p.conj_mem hφ hψ

/-- Universal evaluation preserves ∨. -/
theorem universalEval_disj {α : Type} {T : GeomTheory α}
    (p : Spectrum T) (φ ψ : GeomFormula α) :
    universalEval p (.disj φ ψ) ↔ universalEval p φ ∨ universalEval p ψ := by
  constructor
  · exact p.prime
  · intro h; rcases h with hφ | hψ
    · exact p.upward hφ (Derivable.disj_intro_left _ _)
    · exact p.upward hψ (Derivable.disj_intro_right _ _)

/-! ## Section 9: Summary

This layer establishes:

1. **Spectral topology** (`spectralTopology`): Generated by basic opens D(φ).

2. **Frame structure**: D(φ ∧ ψ) = D(φ) ∩ D(ψ), D(φ ∨ ψ) = D(φ) ∪ D(ψ),
   D(⋁ᵢ φᵢ) = ⋃ᵢ D(φᵢ). The basic opens form a frame.

3. **T₀ separation** (`spectral_T0` ★): Distinct points are topologically
   distinguishable.

4. **Continuity** (`spectralMap_continuous`): Spectral maps are continuous.

5. **Vanishing sets**: V(φ) = D(φ)ᶜ with dual properties.

6. **Universal evaluation**: The evaluation map is a frame homomorphism
   on each fiber, recovering the cpfilter structure.

Key theorems:
- `spectral_T0`: the spectral topology is T₀
- `spectralMap_continuous`: spectral maps are continuous
- `basicOpen_inter/union/iUnion`: basic opens form a frame
- `vanishingSet_disj`: V(φ ∨ ψ) = V(φ) ∩ V(ψ)
-/

end Caramello.TopologicalSpectrum