/-
# Layer 11: Topological Sites & Spatial Geometric Morphisms

This layer instantiates the abstract framework (Layers 1–10) for the
fundamental example: **topological spaces as sites**.

## Central Theme

A topological space X determines a **site** (Opens X, J_X) where:
- Objects = open sets of X
- Morphisms = inclusions
- J_X = open cover topology

A continuous map f : X → Y induces a **geometric morphism** Sh(X) → Sh(Y).
This is Caramello Chapter 2 §2.3 and Chapter 3 §3.1.

## Why This Matters

1. Topological spaces are the *primary* source of Grothendieck toposes
2. The sheaf category Sh(X) is the topos of "variable sets over X"
3. Continuous maps = geometric morphisms is the bridge between
   topology and topos theory
4. The frame of opens = the "locale" — pointless topology begins here

## Connection to the Prop-as-Ω Insight

Opens X is a **frame** (Layer 6), just as Prop is.
The subobject classifier of Sh(X) is the sheaf of local truth values,
which over each open U gives the frame of opens of U.
When X = point, Sh(X) ≅ Set ≅ Type, recovering our model topos.

## DAG Structure

```
  geomMorphOfContinuous (★)
       |
  pullbackPushforwardAdj
       |
  opens_grothendieck   opens_frame
       |                    |
  Opens X (Mathlib)    Frame (Layer 6)

  opensPreimage_comp ← opensPreimage_id
       |                    |
  opensPreimage_sSup ← opensPreimage_inf ← opensPreimage_mono
       |
  pointEval_sSup ← pointEval_inf ← opens_separated_by_points
```

## Proof Shape Classification

| Lemma | Tag | κ |
|-------|-----|---|
| `opens_frame`, `opens_category` | 🧩 atomic | 0 |
| `opensPreimage_top/bot/inf` | 🧩 atomic | 0 |
| `opensPreimage_mono` | 🧩 atomic | 0 |
| `opensPreimage_sSup` | 🌿 local-glue | 2 |
| `opens_frame_distrib` | 🌿 local-glue | 2 |
| `opensPreimage_id/comp` | 🔁 reducible | 1 |
| `pointEval_*` (5 lemmas) | 🧩 atomic | 0 |
| `opens_separated_by_points` | 🧩 atomic | 0 |
| `geomMorphOfContinuous` | 🌌 structural | 3 |
-/
import Mathlib
import RequestProject.Foundations.HeytingOmega
import RequestProject.Foundations.GeometricMorphism

namespace Caramello.TopologicalSite

open CategoryTheory CategoryTheory.Limits TopologicalSpace

/-! ## Section 1: Opens X as a Frame / Site

The open sets of a topological space form a frame (= complete Heyting algebra
satisfying the infinite distributive law). This is the algebraic content of
the Grothendieck topology on Opens X.
-/

/-- The open sets of a topological space form a frame.
    This is the spatial analogue of Prop being a frame (Layer 6). -/
instance opens_frame {X : Type*} [TopologicalSpace X] :
    Order.Frame (Opens X) :=
  Opens.instFrame

/-- Opens X is a complete lattice (needed for site constructions). -/
instance opens_completeLattice {X : Type*} [TopologicalSpace X] :
    CompleteLattice (Opens X) :=
  inferInstance

/-- Opens X form a small category (objects = open sets, morphisms = inclusions). -/
instance opens_category {X : Type*} [TopologicalSpace X] :
    Category (Opens X) :=
  inferInstance

/-- The Grothendieck topology on Opens X generated by open covers. -/
noncomputable def opens_grothendieck (X : Type*) [TopologicalSpace X] :
    GrothendieckTopology (Opens X) :=
  Opens.grothendieckTopology X

/-! ## Section 2: Frame Homomorphisms from Continuous Maps

A continuous map f : X → Y induces a frame homomorphism
f⁻¹ : Opens Y → Opens X (preimage of open sets).
This is a key feature: topology is "frame theory with points".
-/

/-- The preimage of an open set under a continuous map is open. -/
lemma preimage_open {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : X → Y) (hf : Continuous f) (U : Opens Y) :
    IsOpen (f ⁻¹' U.1) :=
  U.2.preimage hf

/-- The preimage functor on opens: f⁻¹ : Opens Y → Opens X.
    This preserves all frame operations (finite ∧, arbitrary ∨). -/
def opensPreimage {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : X → Y) (hf : Continuous f) : Opens Y → Opens X :=
  fun U => ⟨f ⁻¹' U.1, U.2.preimage hf⟩

/-- The preimage functor preserves ⊤ (full space). -/
lemma opensPreimage_top {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : X → Y) (hf : Continuous f) :
    opensPreimage f hf ⊤ = ⊤ := by
  ext x; simp [opensPreimage]

/-- The preimage functor preserves ⊥ (empty set). -/
lemma opensPreimage_bot {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : X → Y) (hf : Continuous f) :
    opensPreimage f hf ⊥ = ⊥ := by
  ext x; simp [opensPreimage]

/-- The preimage functor preserves finite intersections (∧). -/
lemma opensPreimage_inf {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : X → Y) (hf : Continuous f) (U V : Opens Y) :
    opensPreimage f hf (U ⊓ V) = opensPreimage f hf U ⊓ opensPreimage f hf V := by
  ext x; simp [opensPreimage]

/-- The preimage functor preserves arbitrary unions (∨). -/
lemma opensPreimage_sSup {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : X → Y) (hf : Continuous f) (S : Set (Opens Y)) :
    opensPreimage f hf (sSup S) = sSup (opensPreimage f hf '' S) := by
  apply le_antisymm
  · intro x hx
    have : f x ∈ (sSup S : Opens Y) := hx
    rw [Opens.mem_sSup] at this
    obtain ⟨U, hUS, hfxU⟩ := this
    have hxU : x ∈ opensPreimage f hf U := hfxU
    exact (le_sSup (Set.mem_image_of_mem _ hUS) : opensPreimage f hf U ≤ _) hxU
  · apply sSup_le
    rintro W ⟨U, hUS, rfl⟩
    intro x hxV
    show f x ∈ (sSup S : Opens Y)
    rw [Opens.mem_sSup]
    exact ⟨U, hUS, hxV⟩

/-- The preimage functor is monotone (order-preserving). -/
lemma opensPreimage_mono {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : X → Y) (hf : Continuous f) : Monotone (opensPreimage f hf) :=
  fun _ _ hUV _ hx => hUV hx

/-! ## Section 3: Sheaves on Topological Spaces

Sh(X) = Sheaf(Opens X, J_X) is the topos of sheaves on X.
Mathlib provides the Grothendieck topology on Opens X and the
sheaf condition.
-/

/-- The category of presheaves on a topological space. -/
abbrev Presheaf (X : Type*) [TopologicalSpace X] :=
  (Opens X)ᵒᵖ ⥤ Type

/-- The category of sheaves on a topological space (for Type-valued sheaves). -/
abbrev SheafCat (X : Type*) [TopologicalSpace X] :=
  Sheaf (opens_grothendieck X) (Type)

/-! ## Section 4: Continuous Maps Induce Geometric Morphisms

The key theorem: a continuous map f : X → Y gives rise to a
geometric morphism Sh(X) → Sh(Y).

- Direct image f_* : Sh(X) → Sh(Y) sends F ↦ F ∘ f⁻¹
  (evaluate the sheaf on preimages of opens)
- Inverse image f* : Sh(Y) → Sh(X) is the sheafification
  of the presheaf pullback
- The adjunction f* ⊣ f_* holds
- f* preserves finite limits (key geometric morphism condition)

For TopCat objects, Mathlib already has this adjunction.
We expose it in our framework.
-/

section TopCatGeometricMorphism

/-- Continuous maps between topological spaces bundled as TopCat morphisms
    induce geometric morphisms between their sheaf categories.

    This is the fundamental bridge: **topology → topos theory**.

    Caramello Ch.2: "Every continuous map f : X → Y gives rise to a
    geometric morphism Sh(f) : Sh(X) → Sh(Y)." -/
noncomputable def geomMorphOfContinuous
    (A : Type*) [Category A] {FA : A → A → Type*} {CA : A → Type*}
    [∀ X Y : A, FunLike (FA X Y) (CA X) (CA Y)]
    [ConcreteCategory A FA]
    [HasColimits A] [HasLimits A]
    [PreservesLimits (forget A)]
    [PreservesFilteredColimits (forget A)]
    [(forget A).ReflectsIsomorphisms]
    {X Y : TopCat} (f : X ⟶ Y) :
    TopCat.Sheaf.pullback A f ⊣ TopCat.Sheaf.pushforward A f :=
  TopCat.Sheaf.pullbackPushforwardAdjunction A f

end TopCatGeometricMorphism

/-! ## Section 5: Frame-Theoretic View of Opens

The connection between the pointwise frame structure on Prop (Layer 6)
and the frame of opens of a topological space. This is the beginning
of "locale theory" = pointless topology.
-/

/-- The opens of a topological space satisfy the frame distributive law:
    U ∩ (⋃ Vᵢ) = ⋃ (U ∩ Vᵢ). This is the defining property of a frame. -/
lemma opens_frame_distrib {X : Type*} [TopologicalSpace X]
    (U : Opens X) (S : Set (Opens X)) :
    U ⊓ sSup S = sSup ((U ⊓ ·) '' S) := by
  apply le_antisymm
  · intro x ⟨hxU, hxS⟩
    have : x ∈ (sSup S : Opens X) := hxS
    rw [Opens.mem_sSup] at this
    obtain ⟨V, hVS, hxV⟩ := this
    exact (le_sSup (Set.mem_image_of_mem _ hVS) : U ⊓ V ≤ _) ⟨hxU, hxV⟩
  · apply sSup_le
    rintro W ⟨V, hVS, rfl⟩
    intro x ⟨hxU, hxV⟩
    refine ⟨hxU, ?_⟩
    show x ∈ (sSup S : Opens X)
    rw [Opens.mem_sSup]
    exact ⟨V, hVS, hxV⟩

/-- A frame homomorphism from Opens Y to Opens X (given by preimage)
    preserves the frame distributive law. This is immediate since
    opensPreimage preserves inf and sSup separately. -/
lemma opensPreimage_preserves_frame_distrib
    {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]
    (f : X → Y) (hf : Continuous f) (U : Opens Y) (S : Set (Opens Y)) :
    opensPreimage f hf (U ⊓ sSup S) =
    opensPreimage f hf U ⊓ opensPreimage f hf (sSup S) := by
  rw [opensPreimage_inf]

/-! ## Section 6: Locale Theory Foundations

A **locale** is a frame (= complete lattice with infinite distributivity).
Every topological space gives a locale (its frame of opens).
Not every locale comes from a topological space — this is "pointless topology".

Caramello's framework encompasses both spatial and non-spatial toposes.
Locales are the "commutative algebra" of topos theory.
-/

/-- The locale associated to a topological space X is the frame Opens X.
    (In general, a locale is any frame; this is the spatial case.) -/
def localeOfSpace (X : Type*) [TopologicalSpace X] := Opens X

/-- The locale of a space is indeed a frame. -/
instance localeOfSpace_frame {X : Type*} [TopologicalSpace X] :
    Order.Frame (localeOfSpace X) :=
  opens_frame

/-- Prop itself is a two-point locale (the "Sierpinski locale").
    This connects Layer 6 (Prop is a frame) with locale theory. -/
noncomputable def prop_locale : Order.Frame Prop :=
  HeytingOmega.prop_frame

/-- The identity map is continuous and gives the identity frame homomorphism. -/
lemma opensPreimage_id {X : Type*} [TopologicalSpace X] :
    opensPreimage (id : X → X) continuous_id = id := by
  funext U
  exact Opens.ext (Set.preimage_id)

/-- Composition of continuous maps corresponds to composition of preimage maps
    (in reverse order, since preimage is contravariant). -/
lemma opensPreimage_comp {X Y Z : Type*}
    [TopologicalSpace X] [TopologicalSpace Y] [TopologicalSpace Z]
    (f : X → Y) (g : Y → Z) (hf : Continuous f) (hg : Continuous g) :
    opensPreimage f hf ∘ opensPreimage g hg = opensPreimage (g ∘ f) (hg.comp hf) := by
  funext U
  exact Opens.ext rfl

/-! ## Section 7: Points of a Locale

A **point** of a locale L is a frame homomorphism L → Prop.
For the locale of a topological space X, points correspond to
elements of X (the "enough points" condition for spatial locales).

When L = Opens X, a point p : Opens X → Prop is the frame homomorphism
that sends U to the proposition "x ∈ U" for some x : X.
-/

/-- A point of a topological space gives a frame homomorphism
    Opens X → Prop by evaluating membership. -/
def pointEval {X : Type*} [TopologicalSpace X] (x : X) :
    Opens X → Prop :=
  fun U => x ∈ U

/-- Point evaluation preserves ⊤. -/
lemma pointEval_top {X : Type*} [TopologicalSpace X] (x : X) :
    pointEval x ⊤ = True := by
  simp [pointEval]

/-- Point evaluation preserves ⊥. -/
lemma pointEval_bot {X : Type*} [TopologicalSpace X] (x : X) :
    pointEval x ⊥ = False := by
  simp [pointEval]

/-- Point evaluation preserves ∧ (intersection). -/
lemma pointEval_inf {X : Type*} [TopologicalSpace X] (x : X) (U V : Opens X) :
    pointEval x (U ⊓ V) ↔ pointEval x U ∧ pointEval x V := by
  simp [pointEval]

/-- Point evaluation preserves ∨ (union = sSup of pair). -/
lemma pointEval_sup {X : Type*} [TopologicalSpace X] (x : X) (U V : Opens X) :
    pointEval x (U ⊔ V) ↔ pointEval x U ∨ pointEval x V := by
  simp [pointEval, Opens.mem_sup]

/-- Point evaluation preserves arbitrary ∨ (union). -/
lemma pointEval_sSup {X : Type*} [TopologicalSpace X] (x : X) (S : Set (Opens X)) :
    pointEval x (sSup S) ↔ ∃ U ∈ S, pointEval x U := by
  simp [pointEval, Opens.mem_sSup]

/-- Points separate the locale: if two opens are distinguished by some point,
    they are distinct. Equivalently, the spatial locale has "enough points". -/
lemma opens_separated_by_points {X : Type*} [TopologicalSpace X] (U V : Opens X) :
    U = V ↔ ∀ x : X, (x ∈ U ↔ x ∈ V) := by
  constructor
  · rintro rfl; exact fun _ => Iff.rfl
  · intro h; ext x; exact h x

end Caramello.TopologicalSite
